import {
  ContractBuilder,
  defineFunctions,
  requireAccessControl,
  setAccessControl,
  addPausable,
} from '@openzeppelin/wizard';

import {
  LIBS,
  accessOf,
  imp,
  print,
  throwIfInvalid,
  validateCommon,
  validateVaultSettings,
  type ValidationMessages,
} from '@/generator/shared';
import { resolveMorphoMarket } from '@/generator/markets';
import { addYieldBooking } from '@/generator/vaults/harvest';
import { addErc4626Limits } from '@/generator/vaults/limits';
import { BYTES32_RE, FINDING_IDS, IMPORT_PATHS, type FindingId, type GenerateOptions } from '@/types';

/**
 * ERC-4626 vault over Morpho Blue.
 *
 * Morpho's integration surface differs from Aave's in three ways that each have
 * their own finding, so this is not the Aave vault with a different address:
 *
 *   MRPH-VLT-016  supply/withdraw take BOTH `assets` and `shares`, and exactly
 *                 one must be zero. Passing both, or neither, reverts with
 *                 "inconsistent input" — verified in Morpho's ErrorsLib.
 *   MRPH-CB-017   a non-empty `data` argument makes Morpho call back into this
 *                 contract. We pass empty bytes and implement no callback, so
 *                 the surface does not exist.
 *   MRPH-MKT-018  a market is identified by the hash of its parameters. Taking
 *                 them per-call lets a caller point the vault at a market with a
 *                 different oracle or LLTV; pinning them at construction doesn't.
 */

function validate(opts: GenerateOptions): void {
  const messages: ValidationMessages = {};
  validateCommon(opts, messages);
  validateVaultSettings(opts, messages);
  if (opts.morphoMarketId !== undefined && !BYTES32_RE.test(opts.morphoMarketId)) {
    messages.morphoMarketId = 'Must be a 32-byte market id';
  }
  // The contract itself takes the market as constructor arguments and works for
  // any market. The tests and the deploy script, however, have to pin a real one,
  // and there is no registry to resolve it from — so an asset with no catalogued
  // market is refused here, where the message reaches the user, rather than in
  // the test assembler.
  if (!messages.asset && !resolveMorphoMarket(opts.asset, opts.morphoMarketId)) {
    messages.asset = opts.morphoMarketId
      ? 'That market id is not one of the catalogued Morpho Blue markets for this asset'
      : 'No catalogued Morpho Blue market lends this asset. Pick USDC, USDT, WETH or DAI.';
  }
  throwIfInvalid(messages);
}

export function buildMorphoVault(opts: GenerateOptions): {
  contract: ContractBuilder;
  appliedFindingIds: FindingId[];
} {
  validate(opts);

  const applied: FindingId[] = [];
  const c = new ContractBuilder(opts.name);
  c.license = 'MIT';

  c.addParent(imp('ERC4626', IMPORT_PATHS.ERC4626), [{ lit: 'asset_' }]);
  c.addConstructionOnly(imp('ERC20', IMPORT_PATHS.ERC20), [
    { lit: `"${opts.name}"` },
    { lit: `"m${opts.name.slice(0, 10).toUpperCase()}"` },
  ]);
  c.addImportOnly(imp('IMorpho', IMPORT_PATHS.MORPHO));
  c.addImportOnly(imp('MarketParams', IMPORT_PATHS.MORPHO));
  c.addImportOnly(imp('MorphoBalancesLib', IMPORT_PATHS.MORPHO_BALANCES_LIB));
  c.addImportOnly(imp('IERC20', IMPORT_PATHS.IERC20));

  c.addLibrary(imp('SafeERC20', IMPORT_PATHS.SAFE_ERC20), ['IERC20']);
  applied.push(FINDING_IDS.UNCHECKED_EXTERNAL_CALL);

  c.addNatspecTag('title', opts.name);
  c.addNatspecTag(
    'notice',
    'ERC-4626 vault over Morpho Blue generated by HARNESS. Market parameters are pinned at construction and Morpho is never given a callback.',
  );

  addMorphoConstructor(c, opts, applied);
  addMorphoAccounting(c, opts, applied);
  addMorphoDepositWithdraw(c, opts, applied);
  addMorphoLimits(c, opts, applied);
  addMorphoHarvest(c, opts);
  addMorphoSurface(c, opts, applied);

  return { contract: c, appliedFindingIds: applied };
}

export function printMorphoVault(opts: GenerateOptions): string {
  const { contract } = buildMorphoVault(opts);
  return print(contract, [LIBS.morpho]);
}

// ---------------------------------------------------------------------------

/** MRPH-MKT-018 — the market is fixed for the vault's lifetime. */
function addMorphoConstructor(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  c.addConstructorArgument({ type: 'address', name: 'morpho_' });
  c.addConstructorArgument({ type: 'IERC20', name: 'asset_' });
  c.addConstructorArgument({ type: 'address', name: 'collateralToken_' });
  c.addConstructorArgument({ type: 'address', name: 'oracle_' });
  c.addConstructorArgument({ type: 'address', name: 'irm_' });
  c.addConstructorArgument({ type: 'uint256', name: 'lltv_' });

  c.addConstantOrImmutableOrErrorDefinition('IMorpho public immutable MORPHO;');
  c.addConstantOrImmutableOrErrorDefinition('address public immutable COLLATERAL_TOKEN;', [
    '/// @notice MRPH-MKT-018 — the market is pinned here and can never be repointed.',
  ]);
  c.addConstantOrImmutableOrErrorDefinition('address public immutable ORACLE;');
  c.addConstantOrImmutableOrErrorDefinition('address public immutable IRM;');
  c.addConstantOrImmutableOrErrorDefinition('uint256 public immutable LLTV;');

  c.addConstructorCode('MORPHO = IMorpho(morpho_);');
  c.addConstructorCode('COLLATERAL_TOKEN = collateralToken_;');
  c.addConstructorCode('ORACLE = oracle_;');
  c.addConstructorCode('IRM = irm_;');
  c.addConstructorCode('LLTV = lltv_;');
  applied.push(FINDING_IDS.MORPHO_MARKET_PARAMS_UNPINNED);

  setAccessControl(c, accessOf(opts));

  const fns = defineFunctions({
    marketParams: {
      kind: 'public',
      args: [],
      returns: ['MarketParams memory'],
      mutability: 'view',
    },
  });
  c.setFunctionComments(
    [
      '/// @notice The market this vault supplies into, rebuilt from pinned immutables.',
      '/// @dev MRPH-MKT-018 — Morpho identifies a market by the hash of these five fields.',
      '/// @dev Accepting them per-call would let a caller aim the vault at a market with a',
      '/// @dev different oracle or LLTV while every function signature stayed identical.',
    ],
    fns.marketParams,
  );
  c.setFunctionBody(
    [
      'return MarketParams({',
      '    loanToken: asset(),',
      '    collateralToken: COLLATERAL_TOKEN,',
      '    oracle: ORACLE,',
      '    irm: IRM,',
      '    lltv: LLTV',
      '});',
    ],
    fns.marketParams,
  );
}

/** AAVE-VLT-003 carries over unchanged: internal accounting plus virtual shares. */
function addMorphoAccounting(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  c.addStateVariable('uint256 private _managedAssets;', false);

  // MRPH-VLT-016. Morpho's supply/withdraw take assets AND shares and require
  // exactly one to be zero — "inconsistent input" otherwise. Naming the zero
  // makes the intent explicit at every call site instead of a bare literal.
  c.addConstantOrImmutableOrErrorDefinition('uint256 private constant SHARES_UNSET = 0;', [
    '/// @dev MRPH-VLT-016 — Morpho requires exactly one of assets/shares to be zero.',
  ]);
  // MRPH-CB-017. Non-empty data makes Morpho call back into this contract.
  c.addConstantOrImmutableOrErrorDefinition('bytes private constant NO_CALLBACK = "";', [
    '/// @dev MRPH-CB-017 — empty data means Morpho never re-enters this contract.',
    '/// @dev No callback is implemented, so the surface does not exist to be gated.',
  ]);
  applied.push(FINDING_IDS.MORPHO_ASSETS_SHARES_EXCLUSIVE);
  applied.push(FINDING_IDS.MORPHO_CALLBACK_UNGATED);

  const fns = defineFunctions({
    totalAssets: { kind: 'public', args: [], returns: ['uint256'], mutability: 'view' },
    _decimalsOffset: { kind: 'internal', args: [], returns: ['uint8'], mutability: 'pure' },
  });

  c.setFunctionComments(
    [
      '/// @notice Assets under management, tracked internally.',
      '/// @dev AAVE-VLT-003 — deliberately not a live read of the Morpho position.',
      '/// @dev Morpho totals are stale until interest accrues, and a donation of shares',
      '/// @dev would move a live figure without any deposit taking place.',
    ],
    fns.totalAssets,
  );
  c.setFunctionBody(['return _managedAssets;'], fns.totalAssets);
  c.addOverride({ name: 'ERC4626' }, fns.totalAssets);

  const offset = opts.decimalsOffset ?? 6;
  c.setFunctionComments(
    [
      '/// @dev AAVE-VLT-003 — virtual shares, so an empty vault cannot be inflated.',
      `/// @dev At offset ${offset}, seeding the rounding attack costs roughly 10^${offset}`,
      '/// @dev times the deposit the attacker is trying to capture.',
    ],
    fns._decimalsOffset,
  );
  c.setFunctionBody([`return ${offset};`], fns._decimalsOffset);
  c.addOverride({ name: 'ERC4626' }, fns._decimalsOffset);

  applied.push(FINDING_IDS.VAULT_ATOKEN_BALANCE_DENOMINATOR);
  applied.push(FINDING_IDS.VAULT_RECEIVER_OWNER_CONFLATED);

  if (opts.depositCap !== undefined) {
    c.addConstantOrImmutableOrErrorDefinition(
      `uint256 public constant DEPOSIT_CAP = ${opts.depositCap};`,
    );
    c.addConstantOrImmutableOrErrorDefinition(
      'error DepositCapExceeded(uint256 cap, uint256 attempted);',
    );
  }
}

function addMorphoDepositWithdraw(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  const fns = defineFunctions({
    _deposit: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
    _withdraw: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'address', name: 'owner' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
  });

  const depositBody: string[] = [];
  if (opts.depositCap !== undefined) {
    depositBody.push(
      'if (_managedAssets + assets > DEPOSIT_CAP) {',
      '    revert DepositCapExceeded(DEPOSIT_CAP, _managedAssets + assets);',
      '}',
      '',
    );
  }
  depositBody.push(
    '// ERC-4626 pulls from `caller` and mints to `receiver`. AAVE-VLT-011 is not',
    '// conflating those, so the base implementation runs first, unmodified.',
    'super._deposit(caller, receiver, assets, shares);',
    '',
    'IERC20(asset()).forceApprove(address(MORPHO), assets);',
    '',
    '// MRPH-VLT-016 — assets set, shares zero. MRPH-CB-017 — no callback data.',
    'uint256 heldBefore = MorphoBalancesLib.expectedSupplyAssets(MORPHO, marketParams(), address(this));',
    'MORPHO.supply(marketParams(), assets, SHARES_UNSET, address(this), NO_CALLBACK);',
    '',
    '// AAVE-ARITH — credit what the position is actually worth, not what we asked',
    '// Morpho to take. Supplying converts assets to shares rounding DOWN; withdrawing',
    '// converts back rounding UP. Booking the requested figure therefore makes',
    '// totalAssets exceed what the shares can redeem, and the last exit underflows',
    '// inside Morpho itself.',
    'uint256 credited =',
    '    MorphoBalancesLib.expectedSupplyAssets(MORPHO, marketParams(), address(this)) - heldBefore;',
    '_managedAssets += credited;',
  );
  c.setFunctionComments(
    ['/// @dev Supplies into the pinned Morpho market on the way in.'],
    fns._deposit,
  );
  c.setFunctionBody(depositBody, fns._deposit);
  c.addOverride({ name: 'ERC4626' }, fns._deposit);

  c.setFunctionComments(
    [
      "/// @dev AAVE-VLT-004 — Morpho's withdraw returns the amount ACTUALLY withdrawn,",
      '/// @dev which is short when the market is fully borrowed. Crediting the requested',
      '/// @dev figure instead mints value that was never received.',
    ],
    fns._withdraw,
  );
  c.setFunctionBody(
    [
      '// A redeem of dust shares can round to zero assets. Morpho rejects a zero-asset',
      '// withdraw as "inconsistent input", so the market is only asked when there is',
      '// something to ask for; the shares are burned either way.',
      'uint256 withdrawn;',
      'if (assets > 0) {',
      '    (withdrawn,) =',
      '        MORPHO.withdraw(marketParams(), assets, SHARES_UNSET, address(this), address(this));',
      '    if (withdrawn < assets) revert WithdrawShortfall(assets, withdrawn);',
      '    _managedAssets -= withdrawn;',
      '    _clampToPosition();',
      '}',
      'super._withdraw(caller, receiver, owner, withdrawn, shares);',
    ],
    fns._withdraw,
  );
  c.addOverride({ name: 'ERC4626' }, fns._withdraw);
  c.addConstantOrImmutableOrErrorDefinition(
    'error WithdrawShortfall(uint256 requested, uint256 received);',
  );

  applied.push(FINDING_IDS.VAULT_WITHDRAW_RETURN_IGNORED);
  applied.push(FINDING_IDS.RISK_CAPS_AND_PAUSE_REVERTS);

  if (opts.pausable) addPausable(c, accessOf(opts), [fns._deposit]);
}

/**
 * Morpho markets cannot be paused and have no supply cap, so the only limit the
 * market imposes is liquidity: supplied minus borrowed, interest accrued.
 */
function addMorphoLimits(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  addErc4626Limits(c, opts, applied, {
    depositBlocked: [],
    depositRoom: [],
    withdrawBlocked: [],
    liquidity: '_marketLiquidity()',
  });

  const fns = defineFunctions({
    _marketLiquidity: { kind: 'internal', args: [], returns: ['uint256'], mutability: 'view' },
  });
  c.setFunctionComments(
    ['/// @dev What the market can pay out right now: supplied minus borrowed, interest accrued.'],
    fns._marketLiquidity,
  );
  c.setFunctionBody(
    [
      '(uint256 totalSupplyAssets,, uint256 totalBorrowAssets,) =',
      '    MorphoBalancesLib.expectedMarketBalances(MORPHO, marketParams());',
      'return totalBorrowAssets >= totalSupplyAssets ? 0 : totalSupplyAssets - totalBorrowAssets;',
    ],
    fns._marketLiquidity,
  );
}

/** Folds accrued Morpho interest into the internal figure; fees accrue and are collected separately. */
function addMorphoHarvest(c: ContractBuilder, opts: GenerateOptions): void {
  addYieldBooking(c, opts, {
    position: 'MorphoBalancesLib.expectedSupplyAssets(MORPHO, marketParams(), address(this))',
    payFee: [
      '(uint256 paid,) =',
      '    MORPHO.withdraw(marketParams(), fee, SHARES_UNSET, address(this), feeRecipient);',
    ],
    notes: ['/// @dev expectedSupplyAssets accrues interest first, so this is not a stale read.'],
  });
}

function addMorphoSurface(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  if (!opts.sweepEscapeHatch) return;

  const fns = defineFunctions({
    sweep: {
      kind: 'external',
      args: [
        { type: 'address', name: 'token' },
        { type: 'address', name: 'to' },
      ],
      mutability: 'nonpayable',
    },
  });
  c.setFunctionComments(
    [
      '/// @notice AAVE-VLT-009 — recover airdrops and dust.',
      '/// @dev The principal is excluded. A hatch that can reach it is the vulnerability.',
      '/// @dev Also the exit for zero-LTV dust pushed here by a griefer (AAVE-RISK-006).',
    ],
    fns.sweep,
  );
  c.setFunctionBody(
    [
      'if (token == asset()) revert CannotSweepPrincipal(token);',
      '',
      'uint256 balance = IERC20(token).balanceOf(address(this));',
      'IERC20(token).safeTransfer(to, balance);',
      'emit Swept(token, to, balance);',
    ],
    fns.sweep,
  );
  c.addConstantOrImmutableOrErrorDefinition('error CannotSweepPrincipal(address token);');
  c.addConstantOrImmutableOrErrorDefinition(
    'event Swept(address indexed token, address indexed to, uint256 amount);',
  );
  requireAccessControl(c, fns.sweep, accessOf(opts), 'SWEEPER', undefined);
  applied.push(FINDING_IDS.VAULT_NO_ESCAPE_HATCH);
  // Deliberately NOT AAVE-RISK-006. The Aave vault claims it here because sweeping
  // is how you clear LTV-0 poison dust out of a collateral position. Morpho has no
  // aTokens and this vault never posts collateral, so there is no poison-dust
  // mechanic to mitigate — claiming it would be an unearned green tick.
}
