import {
  ContractBuilder,
  defineFunctions,
  requireAccessControl,
  setAccessControl,
  addPausable,
} from '@openzeppelin/wizard';

import { cometFor } from '@/generator/markets';
import {
  accessOf,
  imp,
  print,
  throwIfInvalid,
  validateCommon,
  validateVaultSettings,
  withPreamble,
  type ValidationMessages,
} from '@/generator/shared';
import { addYieldBooking } from '@/generator/vaults/harvest';
import { addErc4626Limits } from '@/generator/vaults/limits';
import { FINDING_IDS, IMPORT_PATHS, type FindingId, type GenerateOptions } from '@/types';

/**
 * ERC-4626 vault over a Compound v3 Comet.
 *
 * Comet is not Aave with a different address. Three things are different enough
 * to carry their own finding:
 *
 *   CMPD-VLT-019  `withdraw(base, amount)` has no "amount <= balance" check. If
 *                 the account holds collateral, an over-withdraw SILENTLY OPENS A
 *                 BORROW — and `supplyTo(vault, collateral, x)` is permissionless,
 *                 so anyone can hand the vault collateral. Every withdraw here is
 *                 capped at the supplied balance, and the position is asserted
 *                 non-negative afterwards.
 *   CMPD-VLT-020  balances are present values that round DOWN on every supply and
 *                 withdraw, by up to a base unit. The vault books what the position
 *                 actually moved by, never the amount it asked for.
 *   CMPD-VLT-021  COMP accrues to the Comet account — the vault — and can only be
 *                 claimed to a third party by the account itself (`claimTo` checks
 *                 `hasPermission(src, msg.sender)`). Without a claim path the
 *                 rewards are stranded forever.
 *
 * Comet ships no importable interface at a compatible pragma (its files are
 * `pragma solidity 0.8.15`, exact), so a minimal one is declared in this file.
 */

const COMET_INTERFACE = `/// @dev The slice of Compound v3's Comet this vault uses. Comet is \`pragma solidity 0.8.15\`
/// @dev exactly and is not published to npm, so the interface is declared here.
interface IComet {
    function supply(address asset, uint256 amount) external;
    function withdraw(address asset, uint256 amount) external;
    function withdrawTo(address to, address asset, uint256 amount) external;
    function accrueAccount(address account) external;
    function balanceOf(address account) external view returns (uint256);
    function borrowBalanceOf(address account) external view returns (uint256);
    function baseToken() external view returns (address);
    function isSupplyPaused() external view returns (bool);
    function isWithdrawPaused() external view returns (bool);
}

/// @dev CometRewards, shared by every Comet on a chain.
interface ICometRewards {
    function claimTo(address comet, address src, address to, bool shouldAccrue) external;
}`;

function validate(opts: GenerateOptions): void {
  const messages: ValidationMessages = {};
  validateCommon(opts, messages);
  validateVaultSettings(opts, messages);
  if (!messages.asset && !cometFor(opts.asset)) {
    messages.asset = 'No Compound v3 Comet lends this asset on Ethereum. Pick USDC, WETH or USDT.';
  }
  throwIfInvalid(messages);
}

export function buildCometVault(opts: GenerateOptions): {
  contract: ContractBuilder;
  appliedFindingIds: FindingId[];
} {
  validate(opts);

  const applied: FindingId[] = [];
  const c = new ContractBuilder(opts.name);
  c.license = 'MIT';

  c.addParent(imp('ERC4626', IMPORT_PATHS.ERC4626), [{ lit: 'asset_' }]);
  c.addConstructionOnly(imp('ERC20', IMPORT_PATHS.ERC20), [
    { lit: `"${opts.name}"` },
    { lit: `"c${opts.name.slice(0, 10).toUpperCase()}"` },
  ]);
  c.addImportOnly(imp('IERC20', IMPORT_PATHS.IERC20));

  c.addLibrary(imp('SafeERC20', IMPORT_PATHS.SAFE_ERC20), ['IERC20']);
  applied.push(FINDING_IDS.UNCHECKED_EXTERNAL_CALL);

  c.addNatspecTag('title', opts.name);
  c.addNatspecTag(
    'notice',
    'ERC-4626 vault over Compound v3 generated by HARNESS. Withdrawals are capped at the supplied balance so the position can never go negative, and the share price comes from internal accounting.',
  );

  addCometConstructor(c, opts, applied);
  addCometAccounting(c, opts, applied);
  addCometDepositWithdraw(c, opts, applied);
  addCometLimits(c, opts, applied);
  addCometHarvest(c, opts);
  addCometSurface(c, opts, applied);

  return { contract: c, appliedFindingIds: applied };
}

export function printCometVault(opts: GenerateOptions): string {
  const { contract } = buildCometVault(opts);
  return withPreamble(print(contract), COMET_INTERFACE);
}

// ---------------------------------------------------------------------------

function addCometConstructor(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  c.addConstructorArgument({ type: 'address', name: 'comet_' });
  c.addConstructorArgument({ type: 'IERC20', name: 'asset_' });

  c.addConstantOrImmutableOrErrorDefinition('IComet public immutable COMET;');
  c.addConstantOrImmutableOrErrorDefinition('error AssetIsNotCometBase(address asset, address base);');

  c.addConstructorCode('COMET = IComet(comet_);');
  c.addConstructorCode(
    '// CMPD-VLT-019 — Comet.supply() moves BOTH base and collateral through the same',
    // continues below
  );
  c.addConstructorCode('// signature. A vault whose asset is one of the Comet\'s collaterals would book');
  c.addConstructorCode('// collateral it can never withdraw as base. Refuse anything but the base token.');
  c.addConstructorCode('address base = COMET.baseToken();');
  c.addConstructorCode('if (address(asset_) != base) revert AssetIsNotCometBase(address(asset_), base);');
  applied.push(FINDING_IDS.COMET_WITHDRAW_OPENS_BORROW);

  setAccessControl(c, accessOf(opts));
}

/** AAVE-VLT-003 carries over: `supplyTo(vault, base, x)` is a donation anyone can make. */
function addCometAccounting(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  c.addStateVariable('uint256 private _managedAssets;', false);

  const fns = defineFunctions({
    totalAssets: { kind: 'public', args: [], returns: ['uint256'], mutability: 'view' },
    _decimalsOffset: { kind: 'internal', args: [], returns: ['uint8'], mutability: 'pure' },
  });

  c.setFunctionComments(
    [
      '/// @notice Assets under management, tracked internally.',
      '/// @dev AAVE-VLT-003 — deliberately NOT COMET.balanceOf(address(this)). Comet\'s',
      '/// @dev supplyTo() lets anyone add to this vault\'s position without touching the',
      '/// @dev vault, which is a free share-price move if the balance were the denominator.',
    ],
    fns.totalAssets,
  );
  c.setFunctionBody(['return _managedAssets;'], fns.totalAssets);
  c.addOverride({ name: 'ERC4626' }, fns.totalAssets);

  const offset = opts.decimalsOffset ?? 6;
  c.setFunctionComments(
    [
      '/// @dev AAVE-VLT-003 — virtual shares, so an empty vault cannot be inflated.',
      `/// @dev At offset ${offset}, seeding the rounding attack costs roughly 10^${offset}`,
      '/// @dev times the deposit the attacker is trying to capture.',
    ],
    fns._decimalsOffset,
  );
  c.setFunctionBody([`return ${offset};`], fns._decimalsOffset);
  c.addOverride({ name: 'ERC4626' }, fns._decimalsOffset);

  applied.push(FINDING_IDS.VAULT_ATOKEN_BALANCE_DENOMINATOR);
  applied.push(FINDING_IDS.VAULT_RECEIVER_OWNER_CONFLATED);

  if (opts.depositCap !== undefined) {
    c.addConstantOrImmutableOrErrorDefinition(
      `uint256 public constant DEPOSIT_CAP = ${opts.depositCap};`,
    );
    c.addConstantOrImmutableOrErrorDefinition(
      'error DepositCapExceeded(uint256 cap, uint256 attempted);',
    );
  }
}

function addCometDepositWithdraw(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  const fns = defineFunctions({
    _deposit: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
    _withdraw: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'address', name: 'owner' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
    _withdrawFromComet: {
      kind: 'internal',
      args: [
        { type: 'uint256', name: 'assets' },
        { type: 'address', name: 'to' },
      ],
      returns: ['uint256'],
      mutability: 'nonpayable',
    },
  });

  const depositBody: string[] = [];
  if (opts.depositCap !== undefined) {
    depositBody.push(
      'if (_managedAssets + assets > DEPOSIT_CAP) {',
      '    revert DepositCapExceeded(DEPOSIT_CAP, _managedAssets + assets);',
      '}',
      '',
    );
  }
  depositBody.push(
    '// ERC-4626 pulls from `caller` and mints to `receiver`. AAVE-VLT-011 is not',
    '// conflating those, so the base implementation runs first, unmodified.',
    'super._deposit(caller, receiver, assets, shares);',
    '',
    'IERC20(asset()).forceApprove(address(COMET), assets);',
    '',
    '// CMPD-VLT-020 — credit what the position actually grew by. Comet stores a',
    '// principal and shows a present value; both conversions round DOWN, so the',
    '// balance after supplying `assets` can be short by a base unit. Booking the',
    '// requested figure would let _managedAssets drift above the real position.',
    'uint256 heldBefore = COMET.balanceOf(address(this));',
    'COMET.supply(asset(), assets);',
    '_managedAssets += COMET.balanceOf(address(this)) - heldBefore;',
  );
  c.setFunctionComments(
    ['/// @dev Supplies into Comet on the way in. Reverts with Paused() if the guardian has halted supply (AAVE-RISK-010).'],
    fns._deposit,
  );
  c.setFunctionBody(depositBody, fns._deposit);
  c.addOverride({ name: 'ERC4626' }, fns._deposit);
  applied.push(FINDING_IDS.COMET_PRESENT_VALUE_ROUNDING);

  c.setFunctionComments(
    ['/// @dev Pulls `assets` out of Comet to this contract, then pays `receiver` via the base implementation.'],
    fns._withdraw,
  );
  c.setFunctionBody(
    [
      '// A redeem of dust shares can round to zero assets; nothing to ask Comet for.',
      'uint256 received = assets > 0 ? _withdrawFromComet(assets, address(this)) : 0;',
      'super._withdraw(caller, receiver, owner, received, shares);',
    ],
    fns._withdraw,
  );
  c.addOverride({ name: 'ERC4626' }, fns._withdraw);

  c.setFunctionComments(
    [
      '/// @dev CMPD-VLT-019 — Comet.withdraw() has no "amount <= balance" check. Past the',
      '/// @dev supplied balance it BORROWS, and it can, because anyone may supplyTo() this',
      '/// @dev contract a collateral position. The withdraw is therefore capped at what',
      '/// @dev the position holds, and the position is asserted non-negative afterwards.',
      '/// @dev AAVE-VLT-004 — the amount received is measured, never assumed.',
    ],
    fns._withdrawFromComet,
  );
  c.setFunctionBody(
    [
      'uint256 held = COMET.balanceOf(address(this));',
      'if (assets > held) revert WithdrawExceedsPosition(assets, held);',
      '',
      'uint256 balanceBefore = IERC20(asset()).balanceOf(to);',
      'COMET.withdrawTo(to, asset(), assets);',
      'uint256 received = IERC20(asset()).balanceOf(to) - balanceBefore;',
      'if (received < assets) revert WithdrawShortfall(assets, received);',
      'if (COMET.borrowBalanceOf(address(this)) != 0) revert PositionWentNegative();',
      '',
      '// CMPD-VLT-020 — the withdraw may have shaved a base unit off the principal on',
      '// top of what was paid out; never let the book exceed the position.',
      '_managedAssets -= assets;',
      '_clampToPosition();',
      'return received;',
    ],
    fns._withdrawFromComet,
  );
  c.addConstantOrImmutableOrErrorDefinition(
    'error WithdrawExceedsPosition(uint256 requested, uint256 held);',
  );
  c.addConstantOrImmutableOrErrorDefinition(
    'error WithdrawShortfall(uint256 requested, uint256 received);',
  );
  c.addConstantOrImmutableOrErrorDefinition('error PositionWentNegative();');
  applied.push(FINDING_IDS.VAULT_WITHDRAW_RETURN_IGNORED);

  if (opts.pausable) addPausable(c, accessOf(opts), [fns._deposit]);
}

/** Comet has no base supply cap; the guardian can pause supply and withdraw independently. */
function addCometLimits(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  addErc4626Limits(c, opts, applied, {
    depositBlocked: ['if (COMET.isSupplyPaused()) return 0;'],
    depositRoom: [],
    withdrawBlocked: ['if (COMET.isWithdrawPaused()) return 0;'],
    // Comet holds the base token itself; what it holds is what it can pay out.
    liquidity: '_min(IERC20(asset()).balanceOf(address(COMET)), COMET.balanceOf(address(this)))',
  });

  const fns = defineFunctions({
    _min: {
      kind: 'internal',
      args: [
        { type: 'uint256', name: 'a' },
        { type: 'uint256', name: 'b' },
      ],
      returns: ['uint256'],
      mutability: 'pure',
    },
  });
  c.setFunctionBody(['return a < b ? a : b;'], fns._min);
}

/** Folds accrued Comet interest into the internal figure; fees accrue and are collected separately. */
function addCometHarvest(c: ContractBuilder, opts: GenerateOptions): void {
  addYieldBooking(c, opts, {
    position: 'COMET.balanceOf(address(this))',
    // The fee leaves through the same guarded path as every other withdrawal, so it
    // is capped at the position and can never open a borrow (CMPD-VLT-019).
    payFee: ['_managedAssets += fee;', 'uint256 paid = _withdrawFromComet(fee, feeRecipient);'],
    notes: [
      '/// @dev balanceOf() computes a fresh index, so this is not a stale read. Reading it',
      '/// @dev HERE is safe: a donation is credited to all holders rather than moving the',
      '/// @dev price against the next depositor, and the decimals offset covers the',
      '/// @dev empty-vault case.',
    ],
  });
}

function addCometSurface(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  if (opts.sweepEscapeHatch) {
    const fns = defineFunctions({
      sweep: {
        kind: 'external',
        args: [
          { type: 'address', name: 'token' },
          { type: 'address', name: 'to' },
        ],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-009 — recover airdrops and dust.',
        '/// @dev The principal and the Comet are excluded. Comet is itself an ERC20 whose',
        '/// @dev transfer() moves the supplied balance, so a hatch that can reach it is',
        '/// @dev the vulnerability.',
      ],
      fns.sweep,
    );
    c.setFunctionBody(
      [
        'if (token == asset() || token == address(COMET)) revert CannotSweepPrincipal(token);',
        '',
        'uint256 balance = IERC20(token).balanceOf(address(this));',
        'IERC20(token).safeTransfer(to, balance);',
        'emit Swept(token, to, balance);',
      ],
      fns.sweep,
    );
    c.addConstantOrImmutableOrErrorDefinition('error CannotSweepPrincipal(address token);');
    c.addConstantOrImmutableOrErrorDefinition(
      'event Swept(address indexed token, address indexed to, uint256 amount);',
    );
    requireAccessControl(c, fns.sweep, accessOf(opts), 'SWEEPER', undefined);
    applied.push(FINDING_IDS.VAULT_NO_ESCAPE_HATCH);
  }

  if (opts.claimRewards) {
    const fns = defineFunctions({
      claimRewards: {
        kind: 'external',
        args: [{ type: 'address', name: 'to' }],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice CMPD-VLT-021 — COMP accrues to this contract\'s Comet account and can',
        '/// @notice only be claimed to a third party by the account itself. Without this',
        '/// @notice path the rewards are stranded.',
        '/// @dev claimTo() checks hasPermission(src, msg.sender); src == msg.sender passes.',
      ],
      fns.claimRewards,
    );
    c.setFunctionBody(
      ['ICometRewards(REWARDS).claimTo(address(COMET), address(this), to, true);'],
      fns.claimRewards,
    );
    c.addConstructorArgument({ type: 'address', name: 'rewards_' });
    c.addConstantOrImmutableOrErrorDefinition('address public immutable REWARDS;');
    c.addConstructorCode('REWARDS = rewards_;');
    requireAccessControl(c, fns.claimRewards, accessOf(opts), 'HARVESTER', undefined);
    applied.push(FINDING_IDS.COMET_REWARDS_UNCLAIMABLE);
  }
}
