import { buildPreset } from '@/generator';
import { scaffoldFor } from '@/generator/attacks/scaffold';
import { CONTRACT_NAME_RE, IMPORT_PATHS, SOLIDITY_PRAGMA, type GenerateOptions } from '@/types';

/**
 * Foundry deploy script. Constructor arguments are read off the same ContractBuilder
 * the contract was printed from, so the script cannot drift from what it deploys.
 *
 * This used to build the flash-loan receiver regardless of preset, which meant
 * every exported vault shipped a script whose constructor call did not match its
 * contract — and `forge build` compiles `script/` too, so the whole download
 * failed on its first command. Going through `buildPreset` and the per-preset
 * scaffold closes that permanently: a new preset either provides its bindings or
 * throws here, in the preview, before anything is downloaded.
 */
const PROTOCOL_LABEL: Record<GenerateOptions['preset'], string> = {
  'aave-v3-erc4626-vault': 'against Aave v3 on Ethereum',
  'morpho-blue-vault': 'against Morpho Blue on Ethereum',
  'compound-v3-vault': 'against Compound v3 on Ethereum',
  'token-sale-launchpad': 'on Ethereum',
  'bonding-curve-launchpad': 'against Uniswap V2 on Ethereum',
  'aave-v3-flashloan-receiver': 'against Aave v3 on Ethereum',
};

export function printDeployScript(opts: GenerateOptions): string {
  if (!CONTRACT_NAME_RE.test(opts.name)) {
    throw new Error(`Refusing to interpolate an invalid contract name: ${opts.name}`);
  }

  const { contract } = buildPreset(opts);
  const { deploy } = scaffoldFor(opts);
  const args = contract.constructorArgs.map((a) => {
    const bound = deploy.bindings[a.name];
    if (!bound) throw new Error(`No deploy binding for constructor argument '${a.name}'`);
    return bound;
  });

  const needsIERC20 = args.some((a) => a.startsWith('IERC20('));

  const lines = [
    '// SPDX-License-Identifier: MIT',
    `pragma solidity ${SOLIDITY_PRAGMA};`,
    '',
    `import {Script, console} from "${IMPORT_PATHS.FORGE_SCRIPT}";`,
    ...(needsIERC20 ? [`import {IERC20} from "${IMPORT_PATHS.IERC20}";`] : []),
    `import {${opts.name}} from "../src/${opts.name}.sol";`,
    '',
    `/// @notice Generated by HARNESS. Deploys ${opts.name} ${PROTOCOL_LABEL[opts.preset]}.`,
    `contract Deploy${opts.name} is Script {`,
    ...deploy.constants.map((l) => `    ${l}`),
    '',
    '    function run() external {',
    '        uint256 pk = vm.envUint("PRIVATE_KEY");',
    '        address deployer = vm.addr(pk);',
    '',
    '        vm.startBroadcast(pk);',
    `        ${opts.name} deployed = new ${opts.name}(${args.join(', ')});`,
    '        vm.stopBroadcast();',
    '',
    `        console.log("${opts.name} deployed at", address(deployed));`,
    '    }',
    '}',
    '',
  ];

  return lines.join('\n');
}
