// Regenerates fixtures/sample-compile.json and fixtures/sample-audit.json from whatever is in
// fixtures/sample-generated.json, so the render fixtures always describe the real generator
// output rather than a hand-written approximation.
// The audit fixture is captured with one mitigation deleted — that is demo step 4's state.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { auditSource } from '../routes/audit.js';
import { compileContract } from '../routes/compile.js';
import type { GeneratedProject } from '../types.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixturesDir = path.resolve(here, '../../../fixtures');
const generatedPath = path.join(fixturesDir, 'sample-generated.json');

if (!fs.existsSync(generatedPath)) {
  console.error('fixtures/sample-generated.json is missing — run harness-web/scripts/fixture.ts first');
  process.exit(1);
}

const project = JSON.parse(fs.readFileSync(generatedPath, 'utf8')) as GeneratedProject;

// --- compile ------------------------------------------------------------------------------------

const compiled = compileContract({
  source: project.contractSource,
  contractName: project.contractName,
});
if (!compiled.ok) {
  console.error('refusing to write a fixture for a contract that does not compile');
  for (const e of compiled.errors.filter((x) => x.severity === 'error')) console.error(`  ${e.message.split('\n')[0]}`);
  process.exit(1);
}

// The full bytecode is tens of KB and adds nothing to a render fixture.
const bytecodePreview = `${compiled.bytecode!.slice(0, 130)}…`;
fs.writeFileSync(
  path.join(fixturesDir, 'sample-compile.json'),
  JSON.stringify(
    {
      _note:
        `agent-b fixture · REAL output of POST /compile for ${project.contractName} (${project.preset}), ` +
        `generated by harness-web and compiled with solc via the Aave + OpenZeppelin sources on disk. ` +
        `Regenerate with: npm run fixtures:refresh. bytecode is truncated for readability; the live response returns it in full.`,
      ok: compiled.ok,
      abi: compiled.abi,
      bytecode: bytecodePreview,
      sizeBytes: compiled.sizeBytes,
      errors: compiled.errors,
    },
    null,
    2,
  ) + '\n',
);

// --- audit --------------------------------------------------------------------------------------

// Pick a mitigation the generated contract actually contains, so the fixture shows a real flip.
const CANDIDATES: { id: string; needle: string }[] = [
  { id: 'AAVE-VLT-003', needle: 'function _decimalsOffset() internal pure override returns (uint8) {' },
  { id: 'AAVE-FL-001', needle: 'if (initiator != address(this)) revert NotSelfInitiated(initiator);' },
];

const hit = CANDIDATES.find((c) => project.contractSource.includes(c.needle));
if (!hit) {
  console.error('no known mitigation found in the generated source; cannot capture a triggered state');
  process.exit(1);
}

const tampered = project.contractSource.replace(hit.needle, '');
const audit = auditSource({ source: tampered, preset: project.preset });

fs.writeFileSync(
  path.join(fixturesDir, 'sample-audit.json'),
  JSON.stringify(
    {
      _note:
        `agent-b fixture · REAL output of POST /audit for ${project.contractName} (${project.preset}) with the ` +
        `${hit.id} mitigation deleted — this is demo step 4's state. Restoring it returns every finding to mitigated. ` +
        `Regenerate with: npm run fixtures:refresh.`,
      ...audit,
    },
    null,
    2,
  ) + '\n',
);

console.log(`sample-compile.json  ${project.contractName} — ${compiled.sizeBytes} B, ${compiled.abi?.length} ABI entries`);
console.log(`sample-audit.json    ${hit.id} deleted → ${audit.score.mitigated} mitigated, ${audit.score.triggered} triggered`);
for (const f of audit.findings.filter((f) => f.status === 'triggered')) {
  console.log(`  triggered: ${f.id} [${f.severity}] ${f.title}`);
}
