import { buildFlashLoanReceiver } from '@/generator/aave/flashLoanReceiver';
import { MAINNET } from '@/generator/attacks/assembleAttackTests';
import { CONTRACT_NAME_RE, IMPORT_PATHS, SOLIDITY_PRAGMA, type GenerateOptions } from '@/types';

/**
 * Foundry deploy script. Constructor arguments are read off the same ContractBuilder
 * the contract was printed from, so the script cannot drift from what it deploys.
 */
const BINDINGS: Record<string, string> = {
  addressesProvider: 'POOL_ADDRESSES_PROVIDER',
  asset_: 'ASSET',
  initialOwner: 'deployer',
  defaultAdmin: 'deployer',
  operator: 'deployer',
  rewardsController: 'REWARDS_CONTROLLER',
};

export function printDeployScript(opts: GenerateOptions): string {
  if (!CONTRACT_NAME_RE.test(opts.name)) {
    throw new Error(`Refusing to interpolate an invalid contract name: ${opts.name}`);
  }

  const { contract } = buildFlashLoanReceiver(opts);
  const args = contract.constructorArgs.map((a) => {
    const bound = BINDINGS[a.name];
    if (!bound) throw new Error(`No deploy binding for constructor argument '${a.name}'`);
    return bound;
  });

  const lines = [
    '// SPDX-License-Identifier: MIT',
    `pragma solidity ${SOLIDITY_PRAGMA};`,
    '',
    `import {Script, console} from "${IMPORT_PATHS.FORGE_TEST.replace('Test.sol', 'Script.sol')}";`,
    `import {${opts.name}} from "../src/${opts.name}.sol";`,
    '',
    `/// @notice Generated by HARNESS. Deploys ${opts.name} against Aave v3 on Ethereum.`,
    `contract Deploy${opts.name} is Script {`,
    `    address constant POOL_ADDRESSES_PROVIDER = ${MAINNET.POOL_ADDRESSES_PROVIDER};`,
    `    address constant ASSET = ${opts.asset ?? MAINNET.USDC};`,
  ];

  if (opts.claimRewards) {
    lines.push(`    address constant REWARDS_CONTROLLER = ${MAINNET.REWARDS_CONTROLLER};`);
  }

  lines.push(
    '',
    '    function run() external {',
    '        uint256 pk = vm.envUint("PRIVATE_KEY");',
    '        address deployer = vm.addr(pk);',
    '',
    '        vm.startBroadcast(pk);',
    `        ${opts.name} deployed = new ${opts.name}(${args.join(', ')});`,
    '        vm.stopBroadcast();',
    '',
    `        console.log("${opts.name} deployed at", address(deployed));`,
    '    }',
    '}',
  );

  return lines.join('\n');
}
