import {
  ContractBuilder,
  defineFunctions,
  printContract,
  requireAccessControl,
  setAccessControl,
  addPausable,
  OptionsError,
} from '@openzeppelin/wizard';

import {
  ADDRESS_RE,
  CONTRACT_NAME_RE,
  FINDING_IDS,
  IMPORT_PATHS,
  type FindingId,
  type GenerateOptions,
} from '@/types';

const AAVE_LIB = { name: 'Aave v3 Core', path: '@aave/core-v3', version: '^1.19.0' };
const imp = (name: string, path: string) => ({ name, path });

/** §5.4 — reject, do not sanitize. Nothing user-supplied reaches a string literal. */
function validate(opts: GenerateOptions): void {
  const messages: Record<string, string> = {};
  if (!CONTRACT_NAME_RE.test(opts.name)) messages.name = 'Not a valid Solidity identifier';
  if (opts.asset !== undefined && !ADDRESS_RE.test(opts.asset)) {
    messages.asset = 'Not a valid checksummed-length address';
  }
  if (opts.depositCap !== undefined && !/^[0-9]{1,40}$/.test(opts.depositCap)) {
    messages.depositCap = 'Must be a bounded decimal integer';
  }
  if (opts.feeBps !== undefined && !(Number.isInteger(opts.feeBps) && opts.feeBps >= 0 && opts.feeBps <= 1000)) {
    messages.feeBps = 'Must be an integer between 0 and 1000';
  }
  if (opts.access === 'none') {
    messages.access = 'A vault holds principal; harvest, sweep and pause must be gated';
  }
  if (Object.keys(messages).length > 0) throw new OptionsError(messages);
}

const accessOf = (opts: GenerateOptions) => (opts.access === 'none' ? false : opts.access);

export function buildErc4626Vault(opts: GenerateOptions): {
  contract: ContractBuilder;
  appliedFindingIds: FindingId[];
} {
  validate(opts);

  const applied: FindingId[] = [];
  const c = new ContractBuilder(opts.name);
  c.license = 'MIT';

  // ERC4626 already inherits ERC20, so only ERC4626 goes in the inheritance list;
  // ERC20's constructor is still reachable and needs the name/symbol.
  c.addParent(imp('ERC4626', IMPORT_PATHS.ERC4626), [{ lit: 'asset_' }]);
  c.addConstructionOnly(imp('ERC20', IMPORT_PATHS.ERC20), [
    { lit: `"${opts.name}"` },
    { lit: `"h${opts.name.slice(0, 10).toUpperCase()}"` },
  ]);
  c.addImportOnly(imp('IPool', IMPORT_PATHS.POOL));
  c.addImportOnly(imp('IPoolAddressesProvider', IMPORT_PATHS.POOL_ADDRESSES_PROVIDER));
  c.addImportOnly(imp('IERC20', IMPORT_PATHS.IERC20));

  c.addLibrary(imp('SafeERC20', IMPORT_PATHS.SAFE_ERC20), ['IERC20']);
  applied.push(FINDING_IDS.UNCHECKED_EXTERNAL_CALL);

  c.addNatspecTag('title', opts.name);
  c.addNatspecTag(
    'notice',
    'ERC-4626 vault over Aave v3 generated by HARNESS. Share price is derived from internal accounting, never from a freely transferable aToken balance.',
  );

  addVaultConstructor(c, opts);
  addAccounting(c, opts, applied);
  addDepositWithdraw(c, opts, applied);
  addHarvest(c, opts, applied);
  addVaultSurface(c, opts, applied);

  return { contract: c, appliedFindingIds: applied };
}

function polish(source: string): string {
  return source
    .replace(/[ \t]+$/gm, '')
    .replace(/^\/\/\/ (title|notice|dev|author) /gm, '/// @$1 ');
}

export function printErc4626Vault(opts: GenerateOptions): string {
  const { contract } = buildErc4626Vault(opts);
  return polish(printContract(contract, { additionalCompatibleLibraries: [AAVE_LIB] }));
}

// ---------------------------------------------------------------------------

function addVaultConstructor(c: ContractBuilder, opts: GenerateOptions): void {
  c.addConstructorArgument({ type: 'address', name: 'addressesProvider' });
  c.addConstructorArgument({ type: 'IERC20', name: 'asset_' });

  c.addConstantOrImmutableOrErrorDefinition('IPool public immutable POOL;');
  c.addConstantOrImmutableOrErrorDefinition('IERC20 public immutable ATOKEN;', [
    '/// @notice Held, never used as the share-price denominator. See AAVE-VLT-003.',
  ]);

  c.addConstructorCode('POOL = IPool(IPoolAddressesProvider(addressesProvider).getPool());');
  c.addConstructorCode('ATOKEN = IERC20(POOL.getReserveData(address(asset_)).aTokenAddress);');

  setAccessControl(c, accessOf(opts));
}

/**
 * AAVE-VLT-003. aTokens are ordinary transferable ERC20s, so anyone can send them
 * to this contract without touching Aave at all. A vault whose totalAssets() reads
 * `aToken.balanceOf(this)` therefore lets an attacker move the share price for free.
 * Two independent defences, because this one is Critical:
 *   1. totalAssets() is internal accounting a donor cannot influence.
 *   2. a decimals offset, so the empty-vault rounding attack has no purchase either.
 */
function addAccounting(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  c.addStateVariable('uint256 private _managedAssets;', false);

  const fns = defineFunctions({
    totalAssets: { kind: 'public', args: [], returns: ['uint256'], mutability: 'view' },
    _decimalsOffset: { kind: 'internal', args: [], returns: ['uint8'], mutability: 'pure' },
  });

  c.setFunctionComments(
    [
      '/// @notice Assets under management, tracked internally.',
      '/// @dev AAVE-VLT-003 — deliberately NOT ATOKEN.balanceOf(address(this)).',
      '/// @dev A donation of aTokens cannot move this number (PoolTogether C4 H-01).',
    ],
    fns.totalAssets,
  );
  c.setFunctionBody(['return _managedAssets;'], fns.totalAssets);
  c.addOverride({ name: 'ERC4626' }, fns.totalAssets);

  c.setFunctionComments(
    ['/// @dev AAVE-VLT-003 — virtual shares, so an empty vault cannot be inflated.'],
    fns._decimalsOffset,
  );
  c.setFunctionBody(['return 6;'], fns._decimalsOffset);
  c.addOverride({ name: 'ERC4626' }, fns._decimalsOffset);

  applied.push(FINDING_IDS.VAULT_ATOKEN_BALANCE_DENOMINATOR);

  // ERC-4626's own caller/receiver/owner split is what keeps these straight; we
  // override the internal hooks and leave the public entry points untouched.
  applied.push(FINDING_IDS.VAULT_RECEIVER_OWNER_CONFLATED);

  if (opts.depositCap !== undefined) {
    c.addConstantOrImmutableOrErrorDefinition(`uint256 public constant DEPOSIT_CAP = ${opts.depositCap};`);
    c.addConstantOrImmutableOrErrorDefinition('error DepositCapExceeded(uint256 cap, uint256 attempted);');
  }
}

function addDepositWithdraw(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  const fns = defineFunctions({
    _deposit: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
    _withdraw: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'address', name: 'owner' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
  });

  const depositBody: string[] = [];
  if (opts.depositCap !== undefined) {
    depositBody.push(
      'if (_managedAssets + assets > DEPOSIT_CAP) {',
      '    revert DepositCapExceeded(DEPOSIT_CAP, _managedAssets + assets);',
      '}',
      '',
    );
  }
  depositBody.push(
    '// ERC-4626 pulls from `caller` and mints to `receiver`. AAVE-VLT-011 is not',
    '// conflating those, so the base implementation runs first, unmodified.',
    'super._deposit(caller, receiver, assets, shares);',
    '',
    'IERC20(asset()).forceApprove(address(POOL), assets);',
    '',
    '// AAVE-ARITH — credit what Aave actually minted, not what we asked it to.',
    "// Aave's scaled balances round DOWN, so `assets` overstates the position by up",
    '// to a wei. Booking the requested figure makes _managedAssets drift above the',
    '// real aToken holding, and the last redeemer cannot get out.',
    '// The delta is measured across our own supply call, so nothing can be donated',
    '// in between — this is not the balance-as-denominator pattern of AAVE-VLT-003.',
    'uint256 heldBefore = ATOKEN.balanceOf(address(this));',
    'POOL.supply(asset(), assets, address(this), 0);',
    '_managedAssets += ATOKEN.balanceOf(address(this)) - heldBefore;',
  );
  c.setFunctionComments(
    ['/// @dev Supplies into Aave on the way in. Reverts cleanly when Aave is capped or frozen (AAVE-RISK-010).'],
    fns._deposit,
  );
  c.setFunctionBody(depositBody, fns._deposit);
  c.addOverride({ name: 'ERC4626' }, fns._deposit);

  c.setFunctionComments(
    [
      '/// @dev AAVE-VLT-004 — Aave\'s withdraw returns the amount ACTUALLY withdrawn,',
      '/// @dev which is less than requested when the reserve is illiquid, capped, frozen',
      '/// @dev or paused. Accounting the requested amount instead is the Connext bug.',
    ],
    fns._withdraw,
  );
  c.setFunctionBody(
    [
      'uint256 received = POOL.withdraw(asset(), assets, address(this));',
      'if (received < assets) revert WithdrawShortfall(assets, received);',
      '',
      '_managedAssets -= received;',
      'super._withdraw(caller, receiver, owner, received, shares);',
    ],
    fns._withdraw,
  );
  c.addOverride({ name: 'ERC4626' }, fns._withdraw);
  c.addConstantOrImmutableOrErrorDefinition('error WithdrawShortfall(uint256 requested, uint256 received);');

  applied.push(FINDING_IDS.VAULT_WITHDRAW_RETURN_IGNORED);
  applied.push(FINDING_IDS.RISK_CAPS_AND_PAUSE_REVERTS);

  if (opts.pausable) {
    addPausable(c, accessOf(opts), [fns._deposit]);
  }
}

/** Folds accrued Aave interest into the internal figure, taking the fee on yield only. */
function addHarvest(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  const fns = defineFunctions({
    harvest: { kind: 'external', args: [], returns: ['uint256'], mutability: 'nonpayable' },
  });

  const body = [
    'uint256 held = ATOKEN.balanceOf(address(this));',
    'if (held <= _managedAssets) return 0;',
    '',
    'uint256 yield_ = held - _managedAssets;',
  ];

  if (opts.feeBps) {
    c.addConstantOrImmutableOrErrorDefinition(`uint16 public constant FEE_BPS = ${opts.feeBps};`);
    c.addStateVariable('address public feeRecipient;', false);
    c.addConstructorArgument({ type: 'address', name: 'feeRecipient_' });
    c.addConstructorCode('feeRecipient = feeRecipient_;');
    body.push(
      'uint256 fee = (yield_ * FEE_BPS) / 10_000;',
      '',
      '_managedAssets = held - fee;',
      'if (fee > 0) {',
      '    uint256 paid = POOL.withdraw(asset(), fee, feeRecipient);',
      '    _managedAssets -= (fee - paid);',
      '}',
      'emit Harvested(yield_, fee);',
      'return yield_;',
    );
    c.addConstantOrImmutableOrErrorDefinition('event Harvested(uint256 yield, uint256 fee);');
  } else {
    body.push(
      '_managedAssets = held;',
      'emit Harvested(yield_, 0);',
      'return yield_;',
    );
    c.addConstantOrImmutableOrErrorDefinition('event Harvested(uint256 yield, uint256 fee);');
  }

  c.setFunctionComments(
    [
      '/// @notice Credits accrued Aave interest to the vault.',
      '/// @dev Reading the aToken balance HERE is safe: a donation is credited to all',
      '/// @dev holders rather than moving the price against the next depositor, and the',
      '/// @dev decimals offset covers the empty-vault case.',
    ],
    fns.harvest,
  );
  c.setFunctionBody(body, fns.harvest);
  requireAccessControl(c, fns.harvest, accessOf(opts), 'HARVESTER', 'harvester');
  applied.push(FINDING_IDS.ORACLE_SCALE_MISMATCH);
}

function addVaultSurface(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  if (opts.sweepEscapeHatch) {
    const fns = defineFunctions({
      sweep: {
        kind: 'external',
        args: [
          { type: 'address', name: 'token' },
          { type: 'address', name: 'to' },
        ],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-009 — recover airdrops and dust.',
        '/// @dev The principal and its aToken are excluded. A sweep that can reach either',
        '/// @dev is not an escape hatch, it is the vulnerability.',
        '/// @dev AAVE-RISK-006 — this is also the exit for a FOREIGN aToken. Anyone can push',
        '/// @dev 1 wei of a zero-LTV aToken here; without a hatch it would sit forever.',
      ],
      fns.sweep,
    );
    c.setFunctionBody(
      [
        'if (token == asset() || token == address(ATOKEN)) revert CannotSweepPrincipal(token);',
        '',
        'uint256 balance = IERC20(token).balanceOf(address(this));',
        'IERC20(token).safeTransfer(to, balance);',
        'emit Swept(token, to, balance);',
      ],
      fns.sweep,
    );
    c.addConstantOrImmutableOrErrorDefinition('error CannotSweepPrincipal(address token);');
    c.addConstantOrImmutableOrErrorDefinition(
      'event Swept(address indexed token, address indexed to, uint256 amount);',
    );
    requireAccessControl(c, fns.sweep, accessOf(opts), 'SWEEPER', undefined);
    applied.push(FINDING_IDS.VAULT_NO_ESCAPE_HATCH);
    // The same hatch is what makes zero-LTV poison dust recoverable. This vault never
    // borrows, and Aave only enforces the zero-LTV rule while an account carries debt.
    applied.push(FINDING_IDS.RISK_LTV0_POISON_DUST);
  }

  if (opts.claimRewards) {
    c.addImportOnly(imp('IRewardsController', IMPORT_PATHS.REWARDS_CONTROLLER));
    const fns = defineFunctions({
      claimRewards: {
        kind: 'external',
        args: [
          { type: 'address[] calldata', name: 'assets' },
          { type: 'address', name: 'to' },
        ],
        returns: ['address[] memory', 'uint256[] memory'],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-008 — RewardsController emissions are lost without this.',
        '/// @dev `assets` must be aToken / debtToken addresses, NOT the underlyings.',
      ],
      fns.claimRewards,
    );
    c.setFunctionBody(
      ['return IRewardsController(REWARDS_CONTROLLER).claimAllRewards(assets, to);'],
      fns.claimRewards,
    );
    c.addConstructorArgument({ type: 'address', name: 'rewardsController' });
    c.addConstantOrImmutableOrErrorDefinition('address public immutable REWARDS_CONTROLLER;');
    c.addConstructorCode('REWARDS_CONTROLLER = rewardsController;');
    requireAccessControl(c, fns.claimRewards, accessOf(opts), 'HARVESTER', undefined);
    applied.push(FINDING_IDS.VAULT_REWARDS_UNCLAIMABLE);
  }
}
