import {
  ContractBuilder,
  defineFunctions,
  requireAccessControl,
  setAccessControl,
  addPausable,
} from '@openzeppelin/wizard';

import {
  LIBS,
  accessOf,
  imp,
  print,
  throwIfInvalid,
  validateCommon,
  validateVaultSettings,
  type ValidationMessages,
} from '@/generator/shared';
import { addYieldBooking } from '@/generator/vaults/harvest';
import { addErc4626Limits } from '@/generator/vaults/limits';
import { FINDING_IDS, IMPORT_PATHS, type FindingId, type GenerateOptions } from '@/types';

function validate(opts: GenerateOptions): void {
  const messages: ValidationMessages = {};
  validateCommon(opts, messages);
  validateVaultSettings(opts, messages);
  throwIfInvalid(messages);
}

export function buildErc4626Vault(opts: GenerateOptions): {
  contract: ContractBuilder;
  appliedFindingIds: FindingId[];
} {
  validate(opts);

  const applied: FindingId[] = [];
  const c = new ContractBuilder(opts.name);
  c.license = 'MIT';

  // ERC4626 already inherits ERC20, so only ERC4626 goes in the inheritance list;
  // ERC20's constructor is still reachable and needs the name/symbol.
  c.addParent(imp('ERC4626', IMPORT_PATHS.ERC4626), [{ lit: 'asset_' }]);
  c.addConstructionOnly(imp('ERC20', IMPORT_PATHS.ERC20), [
    { lit: `"${opts.name}"` },
    { lit: `"h${opts.name.slice(0, 10).toUpperCase()}"` },
  ]);
  c.addImportOnly(imp('IPool', IMPORT_PATHS.POOL));
  c.addImportOnly(imp('IPoolAddressesProvider', IMPORT_PATHS.POOL_ADDRESSES_PROVIDER));
  c.addImportOnly(imp('IERC20', IMPORT_PATHS.IERC20));

  c.addLibrary(imp('SafeERC20', IMPORT_PATHS.SAFE_ERC20), ['IERC20']);
  applied.push(FINDING_IDS.UNCHECKED_EXTERNAL_CALL);

  c.addNatspecTag('title', opts.name);
  c.addNatspecTag(
    'notice',
    'ERC-4626 vault over Aave v3 generated by HARNESS. Share price is derived from internal accounting, never from a freely transferable aToken balance.',
  );

  addVaultConstructor(c, opts);
  addAccounting(c, opts, applied);
  addDepositWithdraw(c, opts, applied);
  addLimits(c, opts, applied);
  addHarvest(c, opts, applied);
  addVaultSurface(c, opts, applied);

  return { contract: c, appliedFindingIds: applied };
}

export function printErc4626Vault(opts: GenerateOptions): string {
  const { contract } = buildErc4626Vault(opts);
  return print(contract, [LIBS.aave, LIBS.aavePeriphery]);
}

// ---------------------------------------------------------------------------

function addVaultConstructor(c: ContractBuilder, opts: GenerateOptions): void {
  c.addConstructorArgument({ type: 'address', name: 'addressesProvider' });
  c.addConstructorArgument({ type: 'IERC20', name: 'asset_' });

  c.addConstantOrImmutableOrErrorDefinition('IPool public immutable POOL;');
  c.addConstantOrImmutableOrErrorDefinition('IERC20 public immutable ATOKEN;', [
    '/// @notice Held, never used as the share-price denominator. See AAVE-VLT-003.',
  ]);

  c.addConstructorCode('POOL = IPool(IPoolAddressesProvider(addressesProvider).getPool());');
  c.addConstructorCode('ATOKEN = IERC20(POOL.getReserveData(address(asset_)).aTokenAddress);');

  setAccessControl(c, accessOf(opts));
}

/**
 * AAVE-VLT-003. aTokens are ordinary transferable ERC20s, so anyone can send them
 * to this contract without touching Aave at all. A vault whose totalAssets() reads
 * `aToken.balanceOf(this)` therefore lets an attacker move the share price for free.
 * Two independent defences, because this one is Critical:
 *   1. totalAssets() is internal accounting a donor cannot influence.
 *   2. a decimals offset, so the empty-vault rounding attack has no purchase either.
 */
function addAccounting(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  c.addStateVariable('uint256 private _managedAssets;', false);

  const fns = defineFunctions({
    totalAssets: { kind: 'public', args: [], returns: ['uint256'], mutability: 'view' },
    _decimalsOffset: { kind: 'internal', args: [], returns: ['uint8'], mutability: 'pure' },
  });

  c.setFunctionComments(
    [
      '/// @notice Assets under management, tracked internally.',
      '/// @dev AAVE-VLT-003 — deliberately NOT ATOKEN.balanceOf(address(this)).',
      '/// @dev A donation of aTokens cannot move this number (PoolTogether C4 H-01).',
    ],
    fns.totalAssets,
  );
  c.setFunctionBody(['return _managedAssets;'], fns.totalAssets);
  c.addOverride({ name: 'ERC4626' }, fns.totalAssets);

  const offset = opts.decimalsOffset ?? 6;
  c.setFunctionComments(
    [
      '/// @dev AAVE-VLT-003 — virtual shares, so an empty vault cannot be inflated.',
      `/// @dev At offset ${offset}, seeding the rounding attack costs the attacker`,
      `/// @dev roughly 10^${offset} times the deposit they are trying to capture.`,
    ],
    fns._decimalsOffset,
  );
  c.setFunctionBody([`return ${offset};`], fns._decimalsOffset);
  c.addOverride({ name: 'ERC4626' }, fns._decimalsOffset);

  applied.push(FINDING_IDS.VAULT_ATOKEN_BALANCE_DENOMINATOR);

  // ERC-4626's own caller/receiver/owner split is what keeps these straight; we
  // override the internal hooks and leave the public entry points untouched.
  applied.push(FINDING_IDS.VAULT_RECEIVER_OWNER_CONFLATED);

  if (opts.depositCap !== undefined) {
    c.addConstantOrImmutableOrErrorDefinition(`uint256 public constant DEPOSIT_CAP = ${opts.depositCap};`);
    c.addConstantOrImmutableOrErrorDefinition('error DepositCapExceeded(uint256 cap, uint256 attempted);');
  }
}

function addDepositWithdraw(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  const fns = defineFunctions({
    _deposit: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
    _withdraw: {
      kind: 'internal',
      args: [
        { type: 'address', name: 'caller' },
        { type: 'address', name: 'receiver' },
        { type: 'address', name: 'owner' },
        { type: 'uint256', name: 'assets' },
        { type: 'uint256', name: 'shares' },
      ],
      mutability: 'nonpayable',
    },
  });

  const depositBody: string[] = [];
  if (opts.depositCap !== undefined) {
    depositBody.push(
      'if (_managedAssets + assets > DEPOSIT_CAP) {',
      '    revert DepositCapExceeded(DEPOSIT_CAP, _managedAssets + assets);',
      '}',
      '',
    );
  }
  depositBody.push(
    '// ERC-4626 pulls from `caller` and mints to `receiver`. AAVE-VLT-011 is not',
    '// conflating those, so the base implementation runs first, unmodified.',
    'super._deposit(caller, receiver, assets, shares);',
    '',
    'IERC20(asset()).forceApprove(address(POOL), assets);',
    '',
    '// AAVE-ARITH — credit what Aave actually minted, not what we asked it to.',
    "// Aave's scaled balances round DOWN, so `assets` overstates the position by up",
    '// to a wei. Booking the requested figure makes _managedAssets drift above the',
    '// real aToken holding, and the last redeemer cannot get out.',
    '// The delta is measured across our own supply call, so nothing can be donated',
    '// in between — this is not the balance-as-denominator pattern of AAVE-VLT-003.',
    'uint256 heldBefore = ATOKEN.balanceOf(address(this));',
    'POOL.supply(asset(), assets, address(this), 0);',
    '_managedAssets += ATOKEN.balanceOf(address(this)) - heldBefore;',
  );
  c.setFunctionComments(
    ['/// @dev Supplies into Aave on the way in. Reverts cleanly when Aave is capped or frozen (AAVE-RISK-010).'],
    fns._deposit,
  );
  c.setFunctionBody(depositBody, fns._deposit);
  c.addOverride({ name: 'ERC4626' }, fns._deposit);

  c.setFunctionComments(
    [
      '/// @dev AAVE-VLT-004 — Aave\'s withdraw returns the amount ACTUALLY withdrawn,',
      '/// @dev which is less than requested when the reserve is illiquid, capped, frozen',
      '/// @dev or paused. Accounting the requested amount instead is the Connext bug.',
    ],
    fns._withdraw,
  );
  c.setFunctionBody(
    [
      '// A full exit asks Aave for everything rather than for an exact figure: the',
      '// scaled-balance conversion can round the exact figure one unit past what is',
      '// held, and Aave would refuse it.',
      '// A redeem of dust shares can round to zero assets; Aave rejects a zero withdraw,',
      '// so the market is only asked when there is something to ask for.',
      'if (assets > 0) {',
      '    uint256 held = ATOKEN.balanceOf(address(this));',
      '    uint256 received = POOL.withdraw(asset(), assets >= held ? type(uint256).max : assets, address(this));',
      '    if (received < assets) revert WithdrawShortfall(assets, received);',
      '    _managedAssets -= assets;',
      '    _clampToPosition();',
      '}',
      'super._withdraw(caller, receiver, owner, assets, shares);',
    ],
    fns._withdraw,
  );
  c.addOverride({ name: 'ERC4626' }, fns._withdraw);
  c.addConstantOrImmutableOrErrorDefinition('error WithdrawShortfall(uint256 requested, uint256 received);');

  applied.push(FINDING_IDS.VAULT_WITHDRAW_RETURN_IGNORED);
  applied.push(FINDING_IDS.RISK_CAPS_AND_PAUSE_REVERTS);

  if (opts.pausable) {
    addPausable(c, accessOf(opts), [fns._deposit]);
  }
}

/**
 * Aave can refuse a supply (reserve inactive, frozen or paused, or at its supply
 * cap) and can be unable to pay a withdrawal (the aToken holds less underlying
 * than is owed). Both are visible on chain, so the limits report them instead of
 * letting the call revert.
 */
function addLimits(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  c.addImportOnly(imp('DataTypes', IMPORT_PATHS.DATA_TYPES));
  c.addLibrary(imp('ReserveConfiguration', IMPORT_PATHS.RESERVE_CONFIGURATION), [
    'DataTypes.ReserveConfigurationMap',
  ]);
  addErc4626Limits(c, opts, applied, {
    depositBlocked: [
      'DataTypes.ReserveConfigurationMap memory cfg = POOL.getConfiguration(asset());',
      'if (!cfg.getActive() || cfg.getFrozen() || cfg.getPaused()) return 0;',
    ],
    depositRoom: [
      'uint256 cap = cfg.getSupplyCap();',
      'if (cap != 0) {',
      '    // Aave counts the cap in whole tokens against the aToken supply.',
      '    uint256 capRaw = cap * 10 ** cfg.getDecimals();',
      '    uint256 supplied = IERC20(address(ATOKEN)).totalSupply();',
      '    room = supplied >= capRaw ? 0 : capRaw - supplied;',
      '}',
    ],
    withdrawBlocked: ['if (POOL.getConfiguration(asset()).getPaused()) return 0;'],
    liquidity: 'IERC20(asset()).balanceOf(address(ATOKEN))',
  });
}

/**
 * Folds accrued Aave interest into the internal figure, taking the fee on yield only.
 *
 * The fee is accrued, not withdrawn: a harvest that tried to pull a dust-sized fee
 * out of Aave would revert (a withdraw whose scaled amount rounds to zero is
 * refused) and block the whole harvest. collectFees() pays the accumulated fee
 * out separately, when it is worth paying.
 */
function addHarvest(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  addYieldBooking(c, opts, {
    position: 'ATOKEN.balanceOf(address(this))',
    payFee: ['uint256 paid = POOL.withdraw(asset(), fee, feeRecipient);'],
    notes: [
      '/// @dev Reading the aToken balance HERE is safe: a donation is credited to all',
      '/// @dev holders rather than moving the price against the next depositor, and the',
      '/// @dev decimals offset covers the empty-vault case.',
    ],
  });
  applied.push(FINDING_IDS.ORACLE_SCALE_MISMATCH);
}

function addVaultSurface(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  if (opts.sweepEscapeHatch) {
    const fns = defineFunctions({
      sweep: {
        kind: 'external',
        args: [
          { type: 'address', name: 'token' },
          { type: 'address', name: 'to' },
        ],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-009 — recover airdrops and dust.',
        '/// @dev The principal and its aToken are excluded. A sweep that can reach either',
        '/// @dev is not an escape hatch, it is the vulnerability.',
        '/// @dev AAVE-RISK-006 — this is also the exit for a FOREIGN aToken. Anyone can push',
        '/// @dev 1 wei of a zero-LTV aToken here; without a hatch it would sit forever.',
      ],
      fns.sweep,
    );
    c.setFunctionBody(
      [
        'if (token == asset() || token == address(ATOKEN)) revert CannotSweepPrincipal(token);',
        '',
        'uint256 balance = IERC20(token).balanceOf(address(this));',
        'IERC20(token).safeTransfer(to, balance);',
        'emit Swept(token, to, balance);',
      ],
      fns.sweep,
    );
    c.addConstantOrImmutableOrErrorDefinition('error CannotSweepPrincipal(address token);');
    c.addConstantOrImmutableOrErrorDefinition(
      'event Swept(address indexed token, address indexed to, uint256 amount);',
    );
    requireAccessControl(c, fns.sweep, accessOf(opts), 'SWEEPER', undefined);
    applied.push(FINDING_IDS.VAULT_NO_ESCAPE_HATCH);
    // The same hatch is what makes zero-LTV poison dust recoverable. This vault never
    // borrows, and Aave only enforces the zero-LTV rule while an account carries debt.
    applied.push(FINDING_IDS.RISK_LTV0_POISON_DUST);
  }

  if (opts.claimRewards) {
    c.addImportOnly(imp('IRewardsController', IMPORT_PATHS.REWARDS_CONTROLLER));
    const fns = defineFunctions({
      claimRewards: {
        kind: 'external',
        args: [
          { type: 'address[] calldata', name: 'assets' },
          { type: 'address', name: 'to' },
        ],
        returns: ['address[] memory', 'uint256[] memory'],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-008 — RewardsController emissions are lost without this.',
        '/// @dev `assets` must be aToken / debtToken addresses, NOT the underlyings.',
      ],
      fns.claimRewards,
    );
    c.setFunctionBody(
      ['return IRewardsController(REWARDS_CONTROLLER).claimAllRewards(assets, to);'],
      fns.claimRewards,
    );
    c.addConstructorArgument({ type: 'address', name: 'rewardsController' });
    c.addConstantOrImmutableOrErrorDefinition('address public immutable REWARDS_CONTROLLER;');
    c.addConstructorCode('REWARDS_CONTROLLER = rewardsController;');
    requireAccessControl(c, fns.claimRewards, accessOf(opts), 'HARVESTER', undefined);
    applied.push(FINDING_IDS.VAULT_REWARDS_UNCLAIMABLE);
  }
}
