import {
  ContractBuilder,
  defineFunctions,
  printContract,
  requireAccessControl,
  setAccessControl,
  addPausable,
  OptionsError,
} from '@openzeppelin/wizard';

import {
  ADDRESS_RE,
  CONTRACT_NAME_RE,
  FINDING_IDS,
  IMPORT_PATHS,
  SOLIDITY_PRAGMA,
  type FindingId,
  type GenerateOptions,
} from '@/types';

/**
 * Aave v3 flash-loan receiver generator.
 *
 * Mirrors the shape of `@openzeppelin/wizard-uniswap-hooks`: accumulate into a
 * ContractBuilder, hand it to `printContract`. No string templates, no AST.
 *
 * Every mitigation below is tagged with the frozen finding ID it closes, so the
 * generator and the audit engine agree on what this code is claimed to survive.
 */

/** Aave's own docs: prefer `flashLoanSimple`, whose premium is 0.05% at launch. */
const AAVE_LIB = {
  name: 'Aave v3 Core',
  path: '@aave/core-v3',
  version: '^1.19.0',
};

const imp = (name: string, path: string) => ({ name, path });

/** §5.4 / CVE-2026-48054 — reject, do not sanitize. */
function validate(opts: GenerateOptions): void {
  const messages: Record<string, string> = {};

  if (!CONTRACT_NAME_RE.test(opts.name)) {
    messages.name = 'Not a valid Solidity identifier';
  }
  if (opts.asset !== undefined && !ADDRESS_RE.test(opts.asset)) {
    messages.asset = 'Not a valid checksummed-length address';
  }
  // Sweeping and reward-claiming both send tokens to a caller-chosen address.
  // Ungated, each is a theft vector, so they cannot coexist with access: 'none'.
  if (opts.access === 'none' && opts.sweepEscapeHatch) {
    messages.sweepEscapeHatch = 'Requires access control — an ungated sweep drains the contract';
  }
  if (opts.access === 'none' && opts.claimRewards) {
    messages.claimRewards = 'Requires access control — an ungated claim redirects rewards';
  }
  // `addPausable` routes pause()/unpause() through `requireAccessControl` too, so the
  // same rewrite applies: an ungated pause is a free denial of service.
  if (opts.access === 'none' && opts.pausable) {
    messages.pausable = 'Requires access control — an ungated pause is a denial of service';
  }
  if (Object.keys(messages).length > 0) {
    throw new OptionsError(messages);
  }
}

const accessOf = (opts: GenerateOptions) => (opts.access === 'none' ? false : opts.access);

/**
 * `requireAccessControl` silently rewrites `false` to `'ownable'`, on the reasonable
 * assumption that a restricted function must be restricted by *something*. That would
 * make `access: 'none'` emit an Ownable contract while the UI claimed otherwise, so
 * we gate the call instead of the argument.
 */
function gate(
  c: ContractBuilder,
  fn: Parameters<typeof requireAccessControl>[1],
  opts: GenerateOptions,
  roleIdPrefix: string,
  roleOwner: string | undefined,
): void {
  const access = accessOf(opts);
  if (access === false) return;
  requireAccessControl(c, fn, access, roleIdPrefix, roleOwner);
}

export function buildFlashLoanReceiver(opts: GenerateOptions): {
  contract: ContractBuilder;
  appliedFindingIds: FindingId[];
} {
  validate(opts);

  const applied: FindingId[] = [];
  const c = new ContractBuilder(opts.name);
  c.license = 'MIT';

  c.addParent(imp('FlashLoanSimpleReceiverBase', IMPORT_PATHS.FLASH_LOAN_SIMPLE_RECEIVER_BASE), [
    { lit: 'IPoolAddressesProvider(addressesProvider)' },
  ]);
  c.addImportOnly(imp('IPoolAddressesProvider', IMPORT_PATHS.POOL_ADDRESSES_PROVIDER));
  c.addImportOnly(imp('IERC20', IMPORT_PATHS.IERC20));

  // AAVE-DEP-015: every token call goes through SafeERC20, so a non-standard
  // ERC20 that returns false instead of reverting cannot pass silently.
  c.addLibrary(imp('SafeERC20', IMPORT_PATHS.SAFE_ERC20), ['IERC20']);
  applied.push(FINDING_IDS.UNCHECKED_EXTERNAL_CALL);

  c.addNatspecTag('title', opts.name);
  c.addNatspecTag(
    'notice',
    'Aave v3 flashLoanSimple receiver generated by HARNESS. The callback is gated to the Pool and to loans this contract itself initiated.',
  );

  addConstructor(c, opts);
  addStrictParams(c, opts, applied);
  addExecuteOperation(c, opts, applied);
  addInitiator(c, opts, applied);
  addOperationalSurface(c, opts, applied);

  return { contract: c, appliedFindingIds: applied };
}

/**
 * Two quirks in `printContract` we have to correct on the way out:
 *   - blank lines inside a function body are emitted with the body's indentation,
 *     leaving trailing whitespace;
 *   - `printNatspecTags` renders `/// ${key} ${value}` verbatim, and `addNatspecTag`
 *     rejects a leading `@` on anything but `@custom:*`. So the `@` has to go back on.
 */
function polish(source: string): string {
  return source
    .replace(/[ \t]+$/gm, '')
    .replace(/^\/\/\/ (title|notice|dev|author) /gm, '/// @$1 ');
}

export function printFlashLoanReceiver(opts: GenerateOptions): string {
  const { contract } = buildFlashLoanReceiver(opts);
  return polish(printContract(contract, { additionalCompatibleLibraries: [AAVE_LIB] }));
}

// ---------------------------------------------------------------------------

function addConstructor(c: ContractBuilder, opts: GenerateOptions): void {
  // §9.1: never hardcode a Pool address — resolve it through the provider, which
  // is what makes the same bytecode valid across chains and market deployments.
  c.addConstructorArgument({ type: 'address', name: 'addressesProvider' });
  c.addConstructorArgument({ type: 'address', name: 'asset_' });

  c.addConstantOrImmutableOrErrorDefinition(
    'IERC20 public immutable ASSET;',
    ['/// @notice The single underlying this receiver is allowed to borrow.'],
  );
  c.addConstructorCode('ASSET = IERC20(asset_);');

  setAccessControl(c, accessOf(opts));
}

/**
 * AAVE-FL-002. The naive tutorial pattern decodes `params` into `(address target,
 * bytes data)` and calls it. That turns an ungated callback into a drain (Mimo).
 * We decode into a fixed struct instead: there is no field an attacker can point
 * at arbitrary calldata.
 */
function addStrictParams(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  const struct = { name: 'FlashParams', comments: [
    '/// @dev Strictly typed. Deliberately carries no `bytes` payload and no call target:',
    '/// arbitrary calldata decoded here is finding AAVE-FL-002 (Mimo `aggregatorSwap`).',
  ], variables: [] as string[] };

  c.addStructVariable(struct, 'uint256 minAmountOut;');
  c.addStructVariable(struct, 'uint256 deadline;');
  if (opts.routerAllowlist) {
    c.addStructVariable(struct, 'address router;');
  }
  applied.push(FINDING_IDS.FLASHLOAN_ATTACKER_PARAMS);

  c.addConstantOrImmutableOrErrorDefinition('error NotPool(address caller);');
  c.addConstantOrImmutableOrErrorDefinition('error NotSelfInitiated(address initiator);');
  c.addConstantOrImmutableOrErrorDefinition('error UnexpectedAsset(address asset);');
  c.addConstantOrImmutableOrErrorDefinition('error DeadlinePassed(uint256 deadline);');
}

function addExecuteOperation(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  const fns = defineFunctions({
    executeOperation: {
      kind: 'external',
      args: [
        { type: 'address', name: 'asset' },
        { type: 'uint256', name: 'amount' },
        { type: 'uint256', name: 'premium' },
        { type: 'address', name: 'initiator' },
        { type: 'bytes calldata', name: 'params' },
      ],
      returns: ['bool'],
      mutability: 'nonpayable',
    },
  });

  c.setFunctionComments(
    [
      '/// @notice Aave calls this after sending `amount` of `asset` to this contract.',
      '/// @dev THREE GATES, all required. Removing any one of them is a Critical finding:',
      '/// @dev  1. AAVE-FL-001 — caller must be the Pool.',
      '/// @dev  2. AAVE-FL-001 — the loan must be one WE initiated. Without this, anyone',
      '/// @dev     can call `Pool.flashLoan` naming this contract as receiver and Aave will',
      '/// @dev     dutifully invoke this callback for them (DODO MarginTrading, Mimo SuperVault).',
      '/// @dev  3. AAVE-FL-002 — `params` decodes to a fixed struct, never to a call target.',
    ],
    fns.executeOperation,
  );

  const body: string[] = [
    'if (msg.sender != address(POOL)) revert NotPool(msg.sender);',
    'if (initiator != address(this)) revert NotSelfInitiated(initiator);',
    'if (asset != address(ASSET)) revert UnexpectedAsset(asset);',
    '',
    'FlashParams memory p = abi.decode(params, (FlashParams));',
    'if (block.timestamp > p.deadline) revert DeadlinePassed(p.deadline);',
    '',
  ];

  if (opts.routerAllowlist) {
    // AAVE-SWP-014 + AAVE-FL-002: the swap leg is the usual drain vector, so the
    // router must be allowlisted and the caller must state a floor on output.
    body.push(
      'if (!allowedRouters[p.router]) revert RouterNotAllowed(p.router);',
      'if (p.minAmountOut == 0) revert MissingSlippageBound();',
      '',
    );
    applied.push(FINDING_IDS.SWAP_MISSING_MIN_AMOUNT_OUT);
  }

  body.push(
    '// >>> Your strategy goes here. It must leave `amount + premium` of ASSET on',
    '// >>> this contract by the time this function returns.',
    '_executeStrategy(amount, premium, p);',
    '',
    'uint256 owed = amount + premium;',
    'if (ASSET.balanceOf(address(this)) < owed) revert RepaymentShortfall(owed);',
    '',
    '// §9.1: Aave PULLS the repayment. Approve, never transfer.',
    'ASSET.forceApprove(address(POOL), owed);',
    'emit FlashLoanExecuted(asset, amount, premium);',
    'return true;',
  );

  c.setFunctionBody(body, fns.executeOperation);

  c.addConstantOrImmutableOrErrorDefinition('error RepaymentShortfall(uint256 owed);');
  c.addConstantOrImmutableOrErrorDefinition(
    'event FlashLoanExecuted(address indexed asset, uint256 amount, uint256 premium);',
  );
  applied.push(FINDING_IDS.FLASHLOAN_CALLBACK_UNGATED);

  const hook = defineFunctions({
    _executeStrategy: {
      kind: 'internal',
      args: [
        { type: 'uint256', name: 'amount' },
        { type: 'uint256', name: 'premium' },
        { type: 'FlashParams memory', name: 'p' },
      ],
      mutability: 'nonpayable',
    },
  });
  c.setFunctionComments(
    [
      '/// @dev Override point. Deliberately a no-op: HARNESS never emits a strategy it',
      '/// @dev cannot prove safe. The gates above hold regardless of what replaces this.',
    ],
    hook._executeStrategy,
  );
  // A function with an empty `code` array is dropped by `printFunction`, so the body
  // has to carry at least one line or the call site above would not resolve.
  c.setFunctionBody(
    [
      '// Funds are already on this contract. Deploy them, then return with at least',
      '// `amount + premium` of ASSET on hand.',
    ],
    hook._executeStrategy,
  );
}

/**
 * AAVE-FL-013. Idle funds sitting on a receiver are repayment for somebody else's
 * flash loan. Restricting initiation, and holding no balance between calls, is the
 * mitigation Aave's own docs ask for.
 */
function addInitiator(c: ContractBuilder, opts: GenerateOptions, applied: FindingId[]): void {
  const fns = defineFunctions({
    initiateFlashLoan: {
      kind: 'external',
      args: [
        { type: 'uint256', name: 'amount' },
        { type: 'FlashParams calldata', name: 'p' },
      ],
      mutability: 'nonpayable',
    },
  });

  c.setFunctionComments(
    [
      '/// @notice Entry point. Only an authorised caller may put this contract on the hook.',
      '/// @dev AAVE-FL-013 — this contract is not meant to hold an idle balance between',
      '/// @dev calls; an idle balance is what repays an attacker\'s loan.',
      '/// @dev §8.1 — `flashLoanSimple` is used deliberately: the multi-asset `flashLoan`',
      '/// @dev with interestRateModes = 2 OPENS DEBT instead of repaying.',
    ],
    fns.initiateFlashLoan,
  );

  c.setFunctionBody(
    [
      'POOL.flashLoanSimple(address(this), address(ASSET), amount, abi.encode(p), 0);',
    ],
    fns.initiateFlashLoan,
  );

  gate(c, fns.initiateFlashLoan, opts, 'OPERATOR', 'operator');
  applied.push(FINDING_IDS.FLASHLOAN_IDLE_FUNDS);

  if (opts.pausable) {
    // AAVE-RISK-010: caps, freezes and pauses make Aave revert. A local kill switch
    // lets an operator stop initiating rather than discovering it mid-loop.
    addPausable(c, accessOf(opts), [fns.initiateFlashLoan]);
    applied.push(FINDING_IDS.RISK_CAPS_AND_PAUSE_REVERTS);
  }
}

function addOperationalSurface(
  c: ContractBuilder,
  opts: GenerateOptions,
  applied: FindingId[],
): void {
  if (opts.routerAllowlist) {
    c.addStateVariable('mapping(address router => bool allowed) public allowedRouters;', false);
    c.addConstantOrImmutableOrErrorDefinition('error RouterNotAllowed(address router);');
    c.addConstantOrImmutableOrErrorDefinition('error MissingSlippageBound();');
    c.addConstantOrImmutableOrErrorDefinition(
      'event RouterAllowed(address indexed router, bool allowed);',
    );

    const fns = defineFunctions({
      setRouterAllowed: {
        kind: 'external',
        args: [
          { type: 'address', name: 'router' },
          { type: 'bool', name: 'allowed' },
        ],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      ['/// @notice AAVE-SWP-014 — swaps may only route through vetted contracts.'],
      fns.setRouterAllowed,
    );
    c.setFunctionBody(
      ['allowedRouters[router] = allowed;', 'emit RouterAllowed(router, allowed);'],
      fns.setRouterAllowed,
    );
    gate(c, fns.setRouterAllowed, opts, 'ROUTER_ADMIN', undefined);
  }

  if (opts.sweepEscapeHatch) {
    // AAVE-VLT-009. Airdrops, Merkl rewards and dust arrive unannounced; without a
    // hatch they are stuck forever (Morpho integration checklist).
    const fns = defineFunctions({
      sweep: {
        kind: 'external',
        args: [
          { type: 'address', name: 'token' },
          { type: 'address', name: 'to' },
        ],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-009 — recover tokens that arrived outside the strategy.',
        '/// @dev Safe here precisely because this contract holds no principal between',
        '/// @dev flash loans (AAVE-FL-013). On the vault preset this must exclude the asset.',
        '/// @dev AAVE-RISK-006 — also the exit for a zero-LTV aToken pushed here by a griefer.',
      ],
      fns.sweep,
    );
    c.setFunctionBody(
      [
        'uint256 balance = IERC20(token).balanceOf(address(this));',
        'IERC20(token).safeTransfer(to, balance);',
        'emit Swept(token, to, balance);',
      ],
      fns.sweep,
    );
    c.addConstantOrImmutableOrErrorDefinition(
      'event Swept(address indexed token, address indexed to, uint256 amount);',
    );
    gate(c, fns.sweep, opts, 'SWEEPER', undefined);
    applied.push(FINDING_IDS.VAULT_NO_ESCAPE_HATCH);
    // AAVE-RISK-006. Zero-LTV dust is only unrecoverable without a hatch; this receiver
    // also never borrows, which is the other half of why the dust stays inert.
    applied.push(FINDING_IDS.RISK_LTV0_POISON_DUST);
  }

  if (opts.claimRewards) {
    // AAVE-VLT-008. Base yield is not incentives. Rewards accrue to whoever holds
    // the aToken and are lost without a claim path — and you must pass aTokens.
    c.addImportOnly(imp('IRewardsController', IMPORT_PATHS.REWARDS_CONTROLLER));
    const fns = defineFunctions({
      claimRewards: {
        kind: 'external',
        args: [
          { type: 'address[] calldata', name: 'assets' },
          { type: 'address', name: 'to' },
        ],
        returns: ['address[] memory', 'uint256[] memory'],
        mutability: 'nonpayable',
      },
    });
    c.setFunctionComments(
      [
        '/// @notice AAVE-VLT-008 — without this, RewardsController emissions are unclaimable.',
        '/// @dev `assets` must be the aToken / debtToken addresses, NOT the underlyings.',
      ],
      fns.claimRewards,
    );
    c.setFunctionBody(
      ['return IRewardsController(REWARDS_CONTROLLER).claimAllRewards(assets, to);'],
      fns.claimRewards,
    );
    c.addConstructorArgument({ type: 'address', name: 'rewardsController' });
    c.addConstantOrImmutableOrErrorDefinition('address public immutable REWARDS_CONTROLLER;');
    c.addConstructorCode('REWARDS_CONTROLLER = rewardsController;');
    gate(c, fns.claimRewards, opts, 'HARVESTER', undefined);
    applied.push(FINDING_IDS.VAULT_REWARDS_UNCLAIMABLE);
  }

  void SOLIDITY_PRAGMA;
}
