import JSZip from 'jszip';

import { PRESET_LABELS, printPreset } from '@/generator';
import { printDeployScript } from '@/generator/deployScript';
import {
  assembleAttackTests,
  type AssembledTest,
  type AttackSnippetFile,
} from '@/generator/attacks/assembleAttackTests';
import { FORK_BLOCK } from '@/generator/markets';
import { assemblePropertyTests, type PropertyTest } from '@/generator/properties/assemblePropertyTests';
import {
  EVM_VERSION,
  FINDING_TITLES,
  PRESET_CATEGORY,
  REMAPPINGS,
  SOLC_VERSION,
  type FindingId,
  type GenerateOptions,
} from '@/types';

/**
 * A Foundry project the user can actually run, and a Remix link that needs no
 * infrastructure at all.
 *
 * `zipFoundry` from @openzeppelin/wizard is not usable here: the published package
 * requires '../openzeppelin-contracts', which it does not ship. This follows the
 * shape of its source instead.
 */

/**
 * A free archive endpoint that serves state at FORK_BLOCK.
 *
 * A downloaded project must run with no account anywhere, so the default is a
 * public endpoint rather than a hosted fork behind a key. The whole suite was
 * verified against this one; a hosted fork is an optimisation, never a
 * requirement.
 */
export const DEFAULT_RPC = 'https://eth.drpc.org';

const FOUNDRY_TOML = `[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
solc = "${SOLC_VERSION}"
evm_version = "${EVM_VERSION}"
optimizer = true
optimizer_runs = 200

# Free archive RPCs time out under a burst of requests: run the two suites one after
# the other rather than in parallel. If the RPC still times out, add
#   --fork-retries 10 --fork-retry-backoff 1000 --compute-units-per-second 50
# to the forge command.
threads = 1

# The suites fork real mainnet. Point MAINNET_RPC_URL at an archive-capable
# endpoint; the one in .env.example is free and serves the pinned block.
[rpc_endpoints]
mainnet = "\${MAINNET_RPC_URL}"

# Property tests. Fork runs are slow, so the counts are modest; raise them for a
# nightly run. fail_on_revert is deliberate: the handler only performs valid
# actions, so a revert inside one is a finding, not noise.
[fuzz]
runs = 64
max_test_rejects = 65536

[invariant]
runs = 8
depth = 24
fail_on_revert = true
`;

/** The `forge install` lines, chosen by preset so remappings and libs cannot disagree. */
function setupSh(preset: GenerateOptions['preset']): string {
  const base: [string, string][] = [
    ['foundry-rs/forge-std', 'lib/forge-std'],
    ['OpenZeppelin/openzeppelin-contracts', 'lib/openzeppelin-contracts'],
  ];
  const byPreset: Record<GenerateOptions['preset'], [string, string][]> = {
    'aave-v3-erc4626-vault': [
      ['aave/aave-v3-core', 'lib/aave-v3-core'],
      ['aave/aave-v3-periphery', 'lib/aave-v3-periphery'],
    ],
    'aave-v3-flashloan-receiver': [
      ['aave/aave-v3-core', 'lib/aave-v3-core'],
      ['aave/aave-v3-periphery', 'lib/aave-v3-periphery'],
    ],
    'morpho-blue-vault': [['morpho-org/morpho-blue', 'lib/morpho-blue']],
    'compound-v3-vault': [],
    'token-sale-launchpad': [],
    'bonding-curve-launchpad': [],
  };
  const deps = [...base, ...byPreset[preset]];

  const width = Math.max(...deps.map(([repo]) => repo.length));
  const installs = deps
    .map(([repo, path]) => {
      const pad = ' '.repeat(width - repo.length);
      return `forge install ${repo} --no-git --quiet${pad}  # -> ${path}`;
    })
    .join('\n');

  return `#!/usr/bin/env bash
set -euo pipefail

# Generated by HARNESS. Installs the dependencies the generated code imports.
# The install paths below are what remappings.txt expects — changing one means
# changing the other.
${installs}

echo
echo "Now:  cp .env.example .env && forge test -vv"
`;
}

const ENV_EXAMPLE = `# Everything here works with no account anywhere. The RPC below is free and public;
# swap in your own endpoint for anything beyond a trial run.
#
# IMPORTANT: this must be an ARCHIVE endpoint while FORK_BLOCK is set. Most free RPCs
# prune old state and refuse blocks more than ~128 behind head.
MAINNET_RPC_URL=${DEFAULT_RPC}

# Pinned so the suites are reproducible: an unpinned fork drifts with mainnet, and a
# suite that is green today goes red tomorrow for reasons unrelated to the code.
# Set to 0 to fork at the latest block, which works on any RPC including free ones.
FORK_BLOCK=${FORK_BLOCK}

# Only needed for script/*.s.sol broadcasts.
PRIVATE_KEY=
`;

function readme(
  opts: GenerateOptions,
  attacks: AssembledTest[],
  properties: PropertyTest[],
  findingIds: string[],
): string {
  const category = PRESET_CATEGORY[opts.preset];
  const what =
    category === 'vault'
      ? 'An ERC-4626 vault over a live lending market'
      : category === 'launchpad'
        ? 'A token launchpad contract'
        : 'An Aave v3 flash-loan receiver';
  const fuzz = properties.filter((p) => p.kind === 'fuzz');
  const invariants = properties.filter((p) => p.kind === 'invariant');

  return `# ${opts.name}

Generated by [HARNESS](https://harness-web-livid.vercel.app) — the wizard that ships
the attacks on the code it writes.

## What this is

${what} (${PRESET_LABELS[opts.preset]}), hardened against ${findingIds.length} documented
findings, plus two Foundry suites that run against the real protocol on a fork of mainnet.

| File | |
|---|---|
| \`src/${opts.name}.sol\` | the contract |
| \`test/${opts.name}.attack.t.sol\` | ${attacks.length} attack tests, one per mitigation, each citing a real incident |
| \`test/${opts.name}.props.t.sol\` | ${fuzz.length} fuzz tests and ${invariants.length} invariants over whatever you build on top |
| \`script/${opts.name}.s.sol\` | deploy script |

## Run it

\`\`\`bash
./setup.sh
cp .env.example .env    # the default RPC is free and serves the pinned block
forge test -vv
\`\`\`

Run only the fast regressions with \`forge test --match-path 'test/*.attack.t.sol'\`.

## Why there are two suites

**The attack suite is the regression suite for the mitigations.** Every test is
derived from a documented incident and fails when the mitigation it names is
removed. It does not prove the code is safe — it proves the code still has the
defences it shipped with. Delete one and re-run: the matching test goes red.

**The property suite is for what you add.** Its properties hold for the generated
contract and must keep holding for any strategy, hook or feature you layer on top.
Foundry drives them with random inputs and random action sequences, so they exercise
your code, not a fixed example.

${attacks.map((t) => `- \`${t.testName}\` — ${t.findingId}: ${FINDING_TITLES[t.findingId] ?? t.title}`).join('\n')}

${properties.map((p) => `- \`${p.name}\` — ${p.claim}`).join('\n')}

## Findings mitigated

${findingIds.map((f) => `- \`${f}\` — ${FINDING_TITLES[f as FindingId] ?? ''}`).join('\n')}

## Attribution

Findings are mapped to the [evm-hack-registry](https://github.com/sanbir/evm-hack-registry)
and [DeFiHackLabs](https://github.com/SunWeb3Sec/DeFiHackLabs) corpora, tagged with the
[AuditVault](https://github.com/AuditWare/AuditVault) taxonomy. Built on
[OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts).

This generated code is MIT. HARNESS itself is AGPL-3.0.
`;
}

/** Everything a project export contains, before zipping. Also what the UI previews. */
export interface ProjectFiles {
  contract: string;
  attackTests: string;
  propertyTests: string;
  deployScript: string;
  attacks: AssembledTest[];
  properties: PropertyTest[];
}

export function buildProjectFiles(
  opts: GenerateOptions,
  snippets: AttackSnippetFile,
  /** The contract as edited in the browser, if the user changed it. */
  editedContract?: string | null,
): ProjectFiles {
  const attack = assembleAttackTests(opts, snippets);
  const props = assemblePropertyTests(opts);
  return {
    contract: editedContract ?? printPreset(opts),
    attackTests: attack.source,
    propertyTests: props.source,
    deployScript: printDeployScript(opts),
    attacks: attack.tests,
    properties: props.tests,
  };
}

export async function buildProjectZip(
  opts: GenerateOptions,
  snippets: AttackSnippetFile,
  findingIds: string[],
  editedContract?: string | null,
): Promise<Blob> {
  const files = buildProjectFiles(opts, snippets, editedContract);

  const zip = new JSZip();
  zip.file(`src/${opts.name}.sol`, files.contract);
  zip.file(`test/${opts.name}.attack.t.sol`, files.attackTests);
  zip.file(`test/${opts.name}.props.t.sol`, files.propertyTests);
  zip.file(`script/${opts.name}.s.sol`, files.deployScript);
  zip.file('foundry.toml', FOUNDRY_TOML);
  zip.file('remappings.txt', REMAPPINGS.join('\n') + '\n');
  zip.file('.env.example', ENV_EXAMPLE);
  zip.file('setup.sh', setupSh(opts.preset), { unixPermissions: '755' });
  zip.file('README.md', readme(opts, files.attacks, files.properties, findingIds));

  return zip.generateAsync({ type: 'blob' });
}

/**
 * Remix reads the contract straight out of the URL fragment. Mechanism per OZ's
 * own `ui/src/solidity/remix.ts`: base64 of the UTF-8 bytes, padding stripped.
 *
 * The remappings are the versioned npm form Remix resolves through unpkg — not the
 * `lib/` paths from remappings.txt, which do not exist in Remix and would have
 * broken every import.
 */
const REMIX_REMAPS = [
  '@openzeppelin/contracts/=@openzeppelin/contracts@5.6.1/',
  '@aave/core-v3/=@aave/core-v3@1.19.3/',
  '@aave/periphery-v3/=@aave/periphery-v3@2.5.2/',
  '@morpho-org/morpho-blue/=@morpho-org/morpho-blue@1.0.0/',
];

export function remixUrl(source: string): string {
  const bytes = new TextEncoder().encode(source);
  let binary = '';
  for (const b of bytes) binary += String.fromCharCode(b);
  const code = btoa(binary).replace(/=*$/, '');

  const remaps = btoa(REMIX_REMAPS.join('\n')).replace(/=*$/, '');
  return (
    `https://remix.ethereum.org/#code=${code}` +
    `&remaps=${remaps}` +
    `&activate=solidity,solidityUnitTesting` +
    `&autoCompile=true` +
    `&version=soljson-v${SOLC_VERSION}+commit.40a35a09`
  );
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
