import { buildPreset } from '@/generator';
import { MAINNET } from '@/generator/attacks/addresses';
import { scaffoldFor } from '@/generator/attacks/scaffold';
import {
  CONTRACT_NAME_RE,
  IMPORT_PATHS,
  SOLIDITY_PRAGMA,
  type FindingId,
  type GenerateOptions,
  type Preset,
} from '@/types';

export { MAINNET };

/**
 * Attack-test assembler (task A5).
 *
 * Keeps only the snippets whose finding ID the generated contract actually
 * mitigates, substitutes placeholders, and emits a Foundry fork test. A snippet
 * that survives filtering but leaves an unknown {{PLACEHOLDER}} behind is a hard
 * error — a silently broken test is worse than no test.
 */

export interface AttackSnippet {
  testName: string;
  title: string;
  presets?: Preset[];
  incidents: { name: string; url: string; pocFolder?: string }[];
  comments?: string[];
  body: string[];
  helpers?: string[];
}

export interface AttackSnippetFile {
  schemaVersion: string;
  snippets: Record<string, AttackSnippet>;
}

export function assembleAttackTests(
  opts: GenerateOptions,
  file: AttackSnippetFile,
): { source: string; testNames: string[]; skipped: FindingId[] } {
  if (!CONTRACT_NAME_RE.test(opts.name)) {
    throw new Error(`Refusing to interpolate an invalid contract name: ${opts.name}`);
  }

  const { contract, appliedFindingIds } = buildPreset(opts);
  const applied = new Set<string>(appliedFindingIds);
  const scaffold = scaffoldFor(opts);

  const chosen: [FindingId, AttackSnippet][] = [];
  const skipped: FindingId[] = [];
  // A finding can carry more than one snippet, keyed '<FINDING_ID>#<variant>' —
  // typically one per preset, since a vault and a flash-loan receiver mitigate the
  // same finding in very different code.
  for (const [key, snippet] of Object.entries(file.snippets)) {
    const id = key.split('#')[0] as FindingId;
    const presetOk = !snippet.presets || snippet.presets.includes(opts.preset);
    if (presetOk && applied.has(id)) chosen.push([id, snippet]);
    else skipped.push(id);
  }

  // A schema mismatch filters every snippet out rather than throwing, so without
  // this the assembler happily emits a test file containing no tests — which looks
  // like success everywhere downstream. Fail loudly instead.
  if (chosen.length === 0) {
    const keys = Object.keys(file.snippets ?? {});
    throw new Error(
      keys.length === 0
        ? `No snippets found. Expected ${file.schemaVersion ?? 'an unknown schema'} with a top-level "snippets" object.`
        : `Emitted 0 tests for preset '${opts.preset}'. ${keys.length} snippet(s) were present but none matched — ` +
          `check that keys are finding IDs (optionally '<ID>#<variant>') and that 'presets' includes this preset.`,
    );
  }

  const ctorArgs = contract.constructorArgs.map((a) => {
    const bound = scaffold.bindings[a.name];
    if (!bound) throw new Error(`No test binding for constructor argument '${a.name}'`);
    return bound;
  });

  const lines: string[] = [
    '// SPDX-License-Identifier: MIT',
    `pragma solidity ${SOLIDITY_PRAGMA};`,
    '',
    `import {Test} from "${IMPORT_PATHS.FORGE_TEST}";`,
    `import {IPool} from "${IMPORT_PATHS.POOL}";`,
    `import {IPoolAddressesProvider} from "${IMPORT_PATHS.POOL_ADDRESSES_PROVIDER}";`,
    `import {IERC20} from "${IMPORT_PATHS.IERC20}";`,
    `import {${opts.name}} from "../src/${opts.name}.sol";`,
    '',
    `/// @title ${opts.name}AttackTest`,
    '/// @notice Generated by HARNESS. Every test below is derived from a documented',
    '/// @notice incident, cited in the comment above it. These run against real Aave',
    '/// @notice on a mainnet fork — not against a mock.',
    `contract ${opts.name}AttackTest is Test {`,
    '    IPoolAddressesProvider internal constant PROVIDER =',
    `        IPoolAddressesProvider(${MAINNET.POOL_ADDRESSES_PROVIDER});`,
    ...scaffold.constants.map((l) => `    ${l}`),
  ];

  if (opts.claimRewards) {
    lines.push(`    address internal constant REWARDS_CONTROLLER = ${MAINNET.REWARDS_CONTROLLER};`);
  }

  lines.push(
    '',
    ...scaffold.state.map((l) => `    ${l}`),
    '',
    '    function setUp() public {',
    '        // No fork block is pinned yet: the Tenderly Virtual Environment forks at',
    '        // latest until TENDERLY_FORK_BLOCK is published. Setting that env var pins',
    '        // both sides without regenerating anything.',
    '        uint256 forkBlock = vm.envOr("TENDERLY_FORK_BLOCK", uint256(0));',
    '        if (forkBlock == 0) {',
    '            vm.createSelectFork(vm.envString("MAINNET_RPC_URL"));',
    '        } else {',
    '            vm.createSelectFork(vm.envString("MAINNET_RPC_URL"), forkBlock);',
    '        }',
    '',
    ...scaffold.setUp.map((l) => `        ${l}`),
    `        harness = new ${opts.name}(${ctorArgs.join(', ')});`,
    '    }',
    '',
    ...scaffold.helpers.map((l) => (l === '' ? '' : `    ${l}`)),
  );

  for (const [id, snippet] of chosen) {
    lines.push('', ...renderTest(id, snippet, scaffold.subs));
  }
  for (const [, snippet] of chosen) {
    if (snippet.helpers?.length) {
      lines.push('', ...snippet.helpers.map((h) => (h === '' ? '' : `    ${h}`)));
    }
  }

  lines.push('}');

  const source = lines.join('\n');
  const leftover = source.match(/\{\{[A-Z_]+\}\}/g);
  if (leftover) {
    throw new Error(
      `Unsubstituted placeholder(s) in attack tests: ${[...new Set(leftover)].join(', ')}`,
    );
  }

  return { source, testNames: chosen.map(([, s]) => s.testName), skipped };
}

function renderTest(
  id: FindingId,
  snippet: AttackSnippet,
  subs: Record<string, string>,
): string[] {
  const substitute = (s: string) =>
    Object.entries(subs).reduce((acc, [k, v]) => acc.split(k).join(v), s);

  const out: string[] = [`    /// ${id} — ${snippet.title}`];
  for (const c of snippet.comments ?? []) out.push(`    /// ${substitute(c)}`);
  for (const inc of snippet.incidents) {
    out.push(`    /// @dev Incident: ${inc.name} — ${inc.url}`);
    if (inc.pocFolder) {
      out.push(
        `    /// @dev Runnable PoC: https://github.com/sanbir/evm-hack-registry/tree/main/${inc.pocFolder}`,
      );
    }
  }
  out.push(`    function ${snippet.testName}() public {`);
  for (const line of snippet.body) {
    out.push(line === '' ? '' : `        ${substitute(line)}`);
  }
  out.push('    }');
  return out;
}
